### PR TITLE
Fix typo in the getAnalyticsConfigByMeasurementIDs selector.

### PR DESCRIPTION
**Pull request by eugene-manuilov**
## Summary

Addresses issue:

- #6372 

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Comment by techanvil** [comment]
Hey @eugene-manuilov, this fix gets the selector working, but I think that it may need a bit more work. When I test it out, it returns `undefined` for the first couple of calls, indicating the data hasn't been resolved yet, which is fine. However, it returns `null` for the next two calls, indicating that no config has been found (and implying the data has been resolved). It then returns the data on the fifth call.

Ideally, it should not be returning `null` for those calls, because the data is clearly still being resolved. Is it possible to update it so it returns `undefined` in this scenario?

image

Additionally, please can you add a bit more detail to the QAB to make it clear that we need to exercise the selector in QA?

**Review by techanvil — CHANGES_REQUESTED** [review]
Hey @eugene-manuilov, this fix gets the selector working, but I think that it may need a bit more work. When I test it out, it returns `undefined` for the first couple of calls, indicating the data hasn't been resolved yet, which is fine. However, it returns `null` for the next two calls, indicating that no config has been found (and implying the data has been resolved). It then returns the data on the fifth call.

Ideally, it should not be returning `null` for those calls, because the data is clearly still being resolved. Is it possible to update it so it returns `undefined` in this scenario?

image

Additionally, please can you add a bit more detail to the QAB to make it clear that we need to exercise the selector in QA?

**Comment by eugene-manuilov** [comment]
Thanks, @techanvil. I have updated the selector to make sure it waits until everything is resolved. Could you please check it again on your end? I'll update QAB shortly.

**Comment by techanvil** [comment]
> Thanks, @techanvil. I have updated the selector to make sure it waits until everything is resolved. Could you please check it again on your end? I'll update QAB shortly.

Thanks @eugene-manuilov. I've tested and it LGTM, returning `unresolved` until there is data. :shipit:

**Review by techanvil — APPROVED** [review]
LGTM! Nice one, @eugene-manuilov.

BTW, I added an extra point to the QAB.

**Pull request merged**
