### PR TITLE
Update translation of formatted strings with multiple placeholders.

### PR DESCRIPTION
**Pull request by sashadoes**
## Summary

Addresses issue:

- #5463 

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [x] Ensure the PR has the correct target branch.
- [x] Double-check that the PR is okay to be merged.
- [x] Ensure the corresponding issue has a ZenHub release assigned.
- [x] Add a changelog message to the issue.

### CODE REVIEW

**Review by hussain-t — CHANGES_REQUESTED** [review]
Thanks, @sashadoes. LGTM. However, before moving this to MR, could you add more details to the QAB?

**Comment by sashadoes** [comment]
> Thanks, @sashadoes. LGTM. However, before moving this to MR, could you add more details to the QAB?

Thanks. I put a more explicit QA Brief. Please check it @hussain-t

**Review by hussain-t — APPROVED** [review]
LGTM 👍

**Review by techanvil — APPROVED** [review]
LGTM, nice cleanup job @sashadoes

**Pull request merged**
