### PR TITLE
Disable AdSense Site Status link when loading.

### PR DESCRIPTION
**Pull request by jimmymadon**
## Summary

Addresses issue:

- #5410 

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by tofumatt — CHANGES_REQUESTED** [review]
Unfortunately looks like the suggestion made in the issue doesn't really work here: a "disabled" link is still clickable as it still creates a link to the value in the `href` prop: 

CleanShot 2022-09-05 at 23 08 30

It looks like we should probably be rendering that component as an entirely different element when we don't want it to be a link. Arguably this is a bug in our `Link` component, where we shouldn't be rendering an `<a>` tag when it's disabled. 🤔

Personally I'd be fine fixing that bug as part of this issue, but we should thoroughly QA it and check through the repo for existing `<Link disabled />` usage to make sure there aren't any regressions.

Oh, and the "External" link indicator should either not be shown for a disabled link or the colour should match the disabled link colour. I lean toward the latter, but I think either would work.

**Comment by aaemnnosttv** [comment]
Good catch @tofumatt. I think all we need to do is swap the `Link` out for a `Button` which should look the same and have the disabled behavior we want. This may have changed with GM2 though as our story looks the same as a regular button 🤔 https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-button--link-button

**Comment by jimmymadon** [comment]
Yup - nice catch @tofumatt!

1. Within Link, we currently render a simple `<a>` in most cases, which does not support the `disabled` attribute (even though we effectively pass the prop as an attribute to the tag). 
2. We render `<button>` (which does support `disabled`) ONLY when the `onClick()` prop is passed AND the `href` prop is NOT passed. 

So as @tofumatt pointed out, a simple fix would be to render a `<button>` if the `disabled` prop is passed - [which is exactly what we have done in the corresponding Button component](https://github.com/google/site-kit-wp/blob/1324367229a56f31b10dddac3f656a38c9f95b00/assets/js/components/Button.js#L65-L66). However, the rendered `<button>` would not support the `external` prop. So instead, I've done another simple fix which is to remove the `href` if the link is `disabled`. And I have used the existing `hideExternalIndicator` prop to hide the icon rather than use a CSS mask to change the colour of the background svg.

**Review by tofumatt — CHANGES_REQUESTED** [review]
So the changes to `Link` and such all look good, but this PR is targeting `main` and looks like it's had `develop` merged into it after the branch was split.

There are changes in here from some other, unrelated PRs not in the release.

@jimmymadon Can you rebase these changes to include only your commits?

**Review by tofumatt — APPROVED** [review]

**Pull request merged**
