### PR TITLE
Removes babel-plugin-makepot package from the build process

### LINKED ISSUE #17: Webpack build throw babel make-pot error
**Describe the bug**
Webpack throw error during build process because of languages/translation.pot not found.  

**To Reproduce**
1. Download the repo
2. Run `npm install && npm run build`
3. See error

**Expected behavior**
Webpack build should success.

**System Information (please complete the following information):**
 - PHP Version: 7.1
 - OS: Mac OSX
 - Browser: Opera
 - Plugin Version: 1.0.0-beta.1

### PR DESCRIPTION
**Pull request by ivankristianto**
## Summary

Currently we have an error with the build process because of the translation.pot not exist anymore.

This PR can be summarized in the following changelog entry:

* Remove translation file generator from build process and the `@wordpress/babel-plugin-makepot` package.

Fixes #17 

## Relevant technical choices
Translation will be handled by polyglots.

## Checklist:
- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by ThierryA** [comment]
@ivankristianto could you open an issue to link this PR to it. As a rule of thumb, we are tracking issues and associating PRs to it.

**Comment by ivankristianto** [comment]
@ThierryA issue open in #17

**Comment by swissspidy** [comment]
This totally makes sense. Plugins eventually ending up on dotorg don‘t need POT files, especially not incomplete JS-only ones.

**Comment by felixarntz** [comment]
@ivankristianto I updated the changelog regarding the following:

* There should only be one changelog message per PR.
* The changelog message should start with an infinitive verb (e.g. "Add", "Remove", "Fix", ...).

Please keep that in mind for the future.

**Pull request merged**
