### PR TITLE
Update Pull Request template.

### PR DESCRIPTION
**Pull request by mitogh**
## Summary

Addresses issue #4424 

By using the list structure instead of a single line structure allow expanding into a better way automatically when GH expands the issue ID.

Image with the example of the automatic expansion from Github, the top link is the issue when using a list, the bottom is the current implementation. 

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by aaemnnosttv** [comment]
Thanks for the PR @mitogh ! This looks like a nice change to me but one that we have to coordinate a little bit if we want to adopt it as we have a script for generating our changelogs for each release which would need to be updated first.

**Comment by mitogh** [comment]
Makes sense I can do some review on those if we are looking to move forward with this change. @aaemnnosttv

**Comment by felixarntz** [comment]
@mitogh Great idea, but like @aaemnnosttv says we need to make adjustments in our script for that first. Also, there should always be an issue to discuss a new enhancement, the pull-request is then only for writing and reviewing the code after it is defined. Could you open an issue where we can proceed with the communication on this?

**Comment by mitogh** [comment]
Thanks @felixarntz @aaemnnosttv 

I've created a new issue to keep track of this:

- #4424

**Review by aaemnnosttv — CHANGES_REQUESTED** [review]
Marking this as requiring changes to make it clear that we're not ready to merge this yet 👍

**Review by felixarntz — APPROVED** [review]
Good to merge now from my end, I'll assign to you @aaemnnosttv to eventually do so.

**Review by aaemnnosttv — APPROVED** [review]

**Pull request merged**
