### PR TITLE
Remove unnecessary full-stop for multiple text lines in GA4 activation banner.

### PR DESCRIPTION
**Pull request by sashadoes**
## Summary

Addresses issue:

- #5927 

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by tofumatt — CHANGES_REQUESTED** [review]
The ACs for this issue were about removing the full-stop/period (eg. `.` character) from the end of each sentence, not removing the message entirely.

That said, I'm not sure that's correct, because these aren't list items—they're marked up as paragraphs and when more than one exists, there should be a full-stop at the end. 🤔

If only one sentence appeared we could follow the Google styleguide to omit the full-stop… but then we'd need to have full-stop AND non full-stop versions of the string, which is kinda wasteful and complicated.

In this case it might be best to change these to `<li>` list items and then remove full-stops from every message. But have multiple paragraphs with a single sentence and no punctuation seems wrong.

My instinct is that this actually _isn't_ an issue and should be closed as a won't fix. I'll check with @marrrmarrr about it 👍🏻 

-----

@sashadoes Side note: when writing QA briefs, can you write them as a set of instructions? In this case, something like:

* Set up Site Kit so the GA4 Activation Banner appears
* The message "You can always add/edit this in the Site Kit Settings" should not end with a full-stop

That makes it easier for the QA person (and any code reviewers) to know exactly how to reproduce the issue and observe its fix.

**Review by tofumatt — CHANGES_REQUESTED** [review]
I thought about this a bit more while writing a message to @marrrmarrr…

Because there are several messages that can appear in the activation banner, removing the full-stop everywhere is a bit complicated; when more than one message appears, we shouldn't be removing it.

There are three options, the from most-to-least complex:

1. Leave the text alone—with one message there is a full-stop at the end of each message. With 2+ messages there is a full-stop at the end of each sentence.
2. Change the text to always omit the full-stop—with one message there is no full-stop at the end of each message. With 2+ messages there is no full-stop at the end of each sentence.
3. Write in logic that checks for the number of messages and displays a full-stop at the end of each sentence only when more than one message exists. We should end each string with an optional full-stop using `sprintf`.

<del>I actually think the best option is the last, but it requires a new set of ACs/IB, because the original issue filed is incomplete. I'm moving this back to ACs for now and will draft up new ones.</del>

Having thought on it further, I think list items is the best way to go here.

**Comment by sashadoes** [comment]
Thanks @tofumatt. I will pick up this again after IB review :)

**Comment by sashadoes** [comment]
Closing this PR, as it is fixed here -> https://github.com/google/site-kit-wp/pull/5997

**Comment by sashadoes** [comment]
https://github.com/google/site-kit-wp/pull/5997

**Pull request closed without merging**
