### PR TITLE
Issue / 7696 Fix GA4 All Traffic Widget Support Links

### PR DESCRIPTION
**Pull request by 10upsimon**
## Summary

Addresses issue:

- #7696

## Relevant technical choices

- Updated file at `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetGA4/UserDimensionsPieChart.js`
    - Updated `otherSupportURL` const to include correct support article path/URI
    - Updated `notSetSupportURL` const to include correct support article path/URI
- Updated GA4 mock data report metrics to include "(other)" in place of "Organic Social"
- Updated applicable JS tests following mock data updates
- Updated applicable VRT reference images following mock data updates

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by eugene-manuilov — APPROVED** [review]

**Review by eugene-manuilov — CHANGES_REQUESTED** [review]
@10upsimon, looks like e2e tests fail, can you take a look why?

**Comment by 10upsimon** [comment]
> @10upsimon, looks like e2e tests fail, can you take a look why?

@eugene-manuilov I believe these are the same failing tests we see (related to timeout and user input) that we have been seeing for some time. I will re-run to make sure.

**Comment by 10upsimon** [comment]
> > @10upsimon, looks like e2e tests fail, can you take a look why?
> 
> @eugene-manuilov I believe these are the same failing tests we see (related to timeout and user input) that we have been seeing for some time. I will re-run to make sure.

@eugene-manuilov we see the same nightly and AMP e2e failing in other PR's, such as https://github.com/google/site-kit-wp/actions/runs/6844850749/job/18609233380?pr=7847 and https://github.com/google/site-kit-wp/actions/runs/6844850749/job/18609232695?pr=7847

The only other one failing here is WordPress Nightly, which may be a failure introduced more recently. I am going to re-run nonetheless.

**Comment by 10upsimon** [comment]
@eugene-manuilov all tests are now passing, assigning back to you and requesting a re-review

**Review by eugene-manuilov — APPROVED** [review]
Awesome! Thanks, @10upsimon.

**Pull request merged**
