### PR TITLE
Check Composer configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
## Summary

Addresses issue #3409

## Relevant technical choices

Change in CI config only.

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by szepeviktor** [comment]
Output

```
./composer.json is valid
```

Okay! :)

**Comment by felixarntz** [comment]
@aaemnnosttv What do you think about this?

**Comment by szepeviktor** [comment]
A good CI checks every byte of every file in the repository.

**Comment by aaemnnosttv** [comment]
@felixarntz I usually include a composer validation check before installing although I wouldn't add a dedicated job for it or anything – it's basically instant.

How about we add it to `.github/workflows/php-lint.yml`?

**Comment by felixarntz** [comment]
> How about we add it to `.github/workflows/php-lint.yml`?

Sounds good.

@szepeviktor Would you be willing to update this PR against the latest Site Kit codebase in the `develop` branch adding it to the `.github/workflows/php-lint.yml` file as @aaemnnosttv suggested?

**Comment by szepeviktor** [comment]
All I could do is in the above linked PR.

**Comment by felixarntz** [comment]
Superseded by #3410.

**Pull request closed without merging**
