### PR TITLE
Retry failed requests: implement exponential backoff.

### PR DESCRIPTION
**Pull request by benbowler**
## Summary

Addresses issue #1998

## Relevant technical choices

Used the `Google_Site_Kit_Client` config as in the IB.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by eugene-manuilov — DISMISSED** [review]
LGTM! :+1:

**Review by aaemnnosttv — CHANGES_REQUESTED** [review]
Thanks @benbowler – looks like this one needs a little more added to the configuration which was missing from the original IB.

See @adamsilverstein 's https://github.com/google/site-kit-wp/issues/1998#issuecomment-713139993

Basically, we want to prevent retrying 500 errors for PageSpeed Insights requests since these are fairly long-running requests that are happening on the server-side and retrying it several times could lead to a request timeout.

We should set a custom retry map that is basically a copy of the default one, with an added key for `lighthouseError` that maps to the "retry never" value. There's a bit more information in the thread on the issue, but let me know if you have any questions and either @adamsilverstein or myself can provide more context for you.

**Comment by benbowler** [comment]
Hey @aaemnnosttv  +  @adamsilverstein, I've added a custom `$retry_map` and pass it to the Google_Client as a config that should now be passed to the REST Runner during the execute function in the library.

**Review by aaemnnosttv — APPROVED** [review]
Great, thanks!

**Pull request merged**
