### PR TITLE
[User Input] Admin settings design

### PR DESCRIPTION
**Pull request by nfmohit**
## Summary

Addresses issue:

- #5896 

## Relevant technical choices

This PR updates the User Input admin settings design to match Figma.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by hussain-t — APPROVED** [review]
Nice one, @nfmohit. LGTM 👍

**Review by tofumatt — CHANGES_REQUESTED** [review]
Following the QA Brief, the CTA doesn't seem to be appearing properly here… it shows for a second, but then disappears:

https://user-images.githubusercontent.com/90871/209009831-c842272a-c687-4dc4-9b2c-6a1634bb7b4d.mp4

I also noticed that an Analytics request is being made when Analytics isn't enabled:

CleanShot 2022-12-21 at 21 53 55

I think that might be related to the CTA not appearing at all (not even for a split-second) when Analytics isn't connected:

https://user-images.githubusercontent.com/90871/209010238-a23b4503-3d13-48d9-869e-e5813b1afa7b.mp4

**Comment by nfmohit** [comment]
Hi, @tofumatt! Thank you for the kind review here.

> the CTA doesn't seem to be appearing properly here… it shows for a second, but then disappears

It looks like @wpdarren noticed this [here](https://github.com/google/site-kit-wp/issues/5895#issuecomment-1354396288) in #5895 but no one was able to replicate it further later on. I have added a comment [there](https://github.com/google/site-kit-wp/issues/5895#issuecomment-1362463940).

> I also noticed that an Analytics request is being made when Analytics isn't enabled

This was also reported [here](https://github.com/google/site-kit-wp/issues/5895#issuecomment-1347947630) in #5895 and @derweili [suggests](https://github.com/google/site-kit-wp/issues/5895#issuecomment-1351014826) this should be addressed in #5933.

How do you think we should proceed here? Thanks!

**Comment by nfmohit** [comment]
@tofumatt Update: @wpdarren will be creating an issue about the CTA disappearing as mentioned [here](https://github.com/google/site-kit-wp/issues/5895#issuecomment-1362627916).

**Review by tofumatt — COMMENTED** [review]
I see the Key Metrics not appearing is filed as #6370, but the current QA Brief mentions looking for that element.

I'm thinking the QA Brief here should be adjusted, but should we consider #6370 as blocking this issue or not? Let me know what you think.

If it's fine to QA the Key Metrics Admin Settings link separately I'm cool with that 🙂

**Comment by nfmohit** [comment]
> I see the Key Metrics not appearing is filed as #6370, but the current QA Brief mentions looking for that element.
> 
> I'm thinking the QA Brief here should be adjusted, but should we consider #6370 as blocking this issue or not? Let me know what you think.
> 
> If it's fine to QA the Key Metrics Admin Settings link separately I'm cool with that 🙂

That's indeed a very valid concern, @tofumatt. I believe it'd be ideal to wait until #6370 is merged, however, keeping in mind that this issue also blocks a large #5897, I have updated the QAB to bypass the check for the CTA.

Let me know what you think. Thanks!

**Comment by nfmohit** [comment]
Understood. Removed this part from the QAB. Thank you @tofumatt!

**Review by tofumatt — APPROVED** [review]
Awesome, thanks! In that case, looks good 👍🏻

**Pull request merged**
