### PR TITLE
Remove pre-WP5.2 PHP polyfill code

### PR DESCRIPTION
**Pull request by nfmohit**
## Summary

Addresses issue:

- #5875 

## Relevant technical choices

This PR removes all PHP polyfill code that is present in the plugin to cater for WordPress versions below 5.2.

### Note for reviewer
The PHP test with WordPress 4.7 fails because we've removed the polyfill code. It is intentional and expected.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [x] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [x] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [x] Ensure the PR has the correct target branch.
- [x] Double-check that the PR is okay to be merged.
- [x] Ensure the corresponding issue has a ZenHub release assigned.
- [x] Add a changelog message to the issue.

### CODE REVIEW

**Review by techanvil — APPROVED** [review]
LGTM, nice one @nfmohit!

Moving to MR, to be merged in the 1.88.0 release.

**Review by tofumatt — APPROVED** [review]
Added a note and moved to the next sprint to further reduce the chance we accidentally merge this 😅

**Review by techanvil — CHANGES_REQUESTED** [review]
@nfmohit unfortunately this has now developed a merge conflict, please could you resolve and ensure the `content-hash` value in `composer.lock` is up-to-date.

**Comment by nfmohit** [comment]
> @nfmohit unfortunately this has now developed a merge conflict, please could you resolve and ensure the `content-hash` value in `composer.lock` is up-to-date.

Fixed merge conflicts. Thank you, @techanvil!

**Review by techanvil — APPROVED** [review]
Thanks @nfmohit! LGTM :+1:

**Pull request merged**
