### PR TITLE
Fix / 6635 Restore User Focus on Account Menu Exit

### PR DESCRIPTION
**Pull request by 10upsimon**
## Summary

Addresses issue:

- #6635

## Relevant technical choices

As per the IB of the linked issue, logic within the `UserMenu` component (located at `assets/js/components/UserMenu/index.js`) was added that effects the following:

* Creates a reference to the DOM element representing the button that triggers the menu open. This was created via `useRef` and assigned to the `Button` component as applicable.
* Enhances the logic of the `useKeyCodesInside` hook that is effecting the `menuWrapperRef` reference object. If the key code is equal to that of `ESCAPE` (i.e, key code `27`) then focus is re-applied to the button element by way of referencing the DOM element using it's reference `menuButtonRef.current` and applying focus via the `focus()` method.
* The menu continues to close as per the pre-existing logic.

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Comment by 10upsimon** [comment]
Realised I handled the the focus logic in a slightly different area to that of the IB, taking a look whether the existing or IB version is better suited.

**Comment by 10upsimon** [comment]
I've had little luck with getting focus applying to the button ref when adding the logic within the `handleMenu` callback. Handling it within the `useKeyCodesInside` hook appears to be more reliable, open to opinions here though.

**Review by eugene-manuilov — CHANGES_REQUESTED** [review]
Thanks, @10upsimon. Although this looks good to me, I think we should probably set the focus to the menu button for all cases when the menu closes, not only when we close it by clicking the escape button. In this case, when the user menu is closed the user can easily open it again.

cc @tofumatt

**Comment by 10upsimon** [comment]
> Thanks, @10upsimon. Although this looks good to me, I think we should probably set the focus to the menu button for all cases when the menu closes, not only when we close it by clicking the escape button. In this case, when the user menu is closed the user can easily open it again.

@eugene-manuilov this has been corrected, thank you. I had actually figured that if we captured this in the tab event as well, that it would cause the menu to be re focussed when the user was trying to move on, but turns out that does not happen. I do note, however, that when closing the menu with tab when it is open, the menu is not re-focussed and the tab order moves on, which I do not think is incorrect, as if the user tabbed out of the menu my opinion is that they're intended to move on.

**Comment by eugene-manuilov** [comment]
@10upsimon, my idea was to restore the focus when the account menu gets closed for other reasons as well (in `handleDialogClose`, `handleMenu`, `handleDialog`, etc). So, no matter how the user closes the account menu, they always can re-open it using keyboard. Does it sound right to you?

cc @tofumatt, would like to hear your thoughts as well.

**Comment by 10upsimon** [comment]
Thank you @eugene-manuilov I re-tested this and I did noticed that when entering into the menu wrapper as far as highlighting a specific menu item, and tabbing out, it does not retain focus. I'm going to see if this can be solved by introducing the `TAB` key const into the `useKeyCodesInside` hook. Failing that, I'll attempt to place logic in the handleDialogClose, handleMenu, handleDialog, etc.

**Comment by 10upsimon** [comment]
@tofumatt assigned you as reviewer based on our slack comms

**Review by tofumatt — APPROVED** [review]
Tested locally and works for me 👍🏻

**Review by tofumatt — APPROVED** [review]
Tested locally and works for me 👍🏻

**Review by tofumatt — APPROVED** [review]
Tested locally and works for me 👍🏻

**Review by tofumatt — APPROVED** [review]
Tested locally and works for me 👍🏻

**Review by tofumatt — APPROVED** [review]
Tested locally and works for me 👍🏻

**Comment by tofumatt** [comment]
Just as a reply to @eugene-manuilov's comments: we should only be re-focusing the button when the menu is closed; if the user exits another way, like pressing the `Tab` key to move to the next element on the page, we don't want to be re-focusing an item they just left.

**Pull request merged**
