### PR TITLE
Expose user input flow in production.

### PR DESCRIPTION
**Pull request by johnPhillips**
## Summary

Addresses issue #2133

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by eugene-manuilov — CHANGES_REQUESTED** [review]
Thanks, @johnPhillips. Mostly it looks good to me but there are still a few places where the userInput flag needs to be deleted:

* The `SettingsAdmin` component checks the `userInput` flag;
* The `SettingsApp.test.js` test file relies on the `userInput` feature.

Could you please take care of it?

**Comment by johnPhillips** [comment]
> The SettingsApp.test.js test file relies on the userInput feature.

@eugene-manuilov Sorry, I'm a bit unclear how to resolve this. Is this whole test file now redundant, or do I need to go through and refactor things?

**Comment by eugene-manuilov** [comment]
@johnPhillips just remove the following line and make sure all javascript tests are passed:

https://github.com/google/site-kit-wp/blob/25d1c1e07fb602744ffb669cb59a52d36e6d9a41/assets/js/components/settings/SettingsApp.test.js#L40

**Comment by johnPhillips** [comment]
Hmmm... when I do that I get 5 failing tests. I must've missed something.

**Comment by felixarntz** [comment]
Superseded by #2894.

**Pull request closed without merging**
