### PR TITLE
Upgrade wp-scripts to latest v-13.

### PR DESCRIPTION
**Pull request by danielgent**
## Summary

Addresses issue #3033

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by tofumatt** [comment]
Are these PRs still relevant? I see this one and:

* #3336
* #3371

But they're all quite old and I'm seeing the issue in the backlog? No worries if any should be kept around but can we tidy up the unneeded ones @danielgent? 🙏🏻

**Comment by danielgent** [comment]
@tofumatt What about escalating this to be in a sprint soon? :smile: 

The ticket mentions trying to upgrade to different version *and* my v15 upgrade does have failing tests, where as the earlier ones don't

The work is already done in these PRs so if we do the ticket then we can close all three

**Comment by danielgent** [comment]
Fine to close this PR and delete this branch if the v17 is approved and merged https://github.com/google/site-kit-wp/pull/3879

**Comment by eugene-manuilov** [comment]
Closing this PR in favor of #3879

**Pull request closed without merging**
