### PR TITLE
Update all copyrights in code to 2021.

### PR DESCRIPTION
**Pull request by johnPhillips**
## Summary
Found and replaced all instances of copyrights from 2019 and 2020 with 2021.

Addresses issue #2511

## Relevant technical choices

N/A

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by aaemnnosttv — CHANGES_REQUESTED** [review]
Thanks @johnPhillips – not much to review here since it's a lot of search/replacements but it looks like there are a few replacements which were missed.

Try doing a project-wide search with this regex: `Copyright 20(?!21)` – I'm seeing 27 files which still need to be updated in JS, 289 in PHP, and 2 scss files on this branch. I would do another search without any file extension filtering when you're done to be extra sure we got them all 😄 

We also have a few instances where the name in the copyright is incorrect – search for "Google Site Kit, Copyright" where this should instead be "Site Kit by Google, Copyright" as per the ACs.

**Comment by johnPhillips** [comment]
Sure thing @aaemnnosttv, let me have another crack at it 👍

**Comment by johnPhillips** [comment]
@aaemnnosttv I can now see the thing that tripped me up with all those PHP files is that the format is different, e.g.
```php
/**
 * Class Google\Site_Kit\Core\Util\Input
 *
 * @package   Google\Site_Kit\Core\Util
 * @copyright 2019 Google LLC
```
With these, should I just replace the year? I.e.

```php
/**
 * Class Google\Site_Kit\Core\Util\Input
 *
 * @package   Google\Site_Kit\Core\Util
 * @copyright 2021 Google LLC
```

**Comment by aaemnnosttv** [comment]
@johnPhillips yes, let's keep the format the same since in PHP we use the doc block format so go ahead and just update the year for those. As for the others though, there were those few instances where the name needed correction (in non-php files) but it was very few.

Also there are merge conflicts here now which will likely continue to be a problem as other PRs are merged. Given the scope of this PR, let's try to finalize it ASAP. It's not marked with the release but I think we should try to merge it as soon as we can to avoid never-ending conflicts+updates.

**Comment by johnPhillips** [comment]
@aaemnnosttv Could you have another look when you have a minute? I can't see any more instances locally. I caught all those PHP ones, and also discovered that the find-and-replace tool I was using ([sd](https://github.com/chmln/sd)) wasn't operating on directories starting with `.` like `.storybook`. So I chased those down as well.
I've used a couple of tools to check, but you never know, another pair of eyes can't hurt.

**Review by tofumatt — APPROVED** [review]
Went through the codebase and couldn't find any old copyright years in any notices.

This is good but has a few merge conflicts that need resolving. After you resolve them feel free to move this into Merge Review and assign @aaemnnosttv.

It might be worth pinging him to get it merged quickly so it isn't blocked again by more merge conflicts given the number of files changed 🙂

**Comment by johnPhillips** [comment]
Merge conflicts fixed, ticket is in MR and @aaemnnosttv is assigned 👍

**Review by aaemnnosttv — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
