### PR TITLE
Opt out of event tracking in E2E tests

### PR DESCRIPTION
**Pull request by aaemnnosttv**
## Summary

Addresses issue #423

## Relevant technical choices

Used `domcontentloaded` instead of `load` as it fires earlier.

## Checklist

- [ ] My code is tested and passes existing unit tests. **n/a**
- [ ] My code has an appropriate set of unit tests which all pass. **n/a**
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.4. **n/a**
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by swissspidy** [comment]
@aaemnnosttv A bunch of tests are failing now

**Comment by aaemnnosttv** [comment]
Strange. I've reverted that last change since it worked fine before that.

**Comment by aaemnnosttv** [comment]
Looks good now @swissspidy !

**Comment by swissspidy** [comment]
`tests/e2e/specs/plugin-activation.test.js` seems to be a bit flaky. Might warrant some investigation there.

**Comment by aaemnnosttv** [comment]
@swissspidy this seems to have broken things. I'm trying a few tweaks to what we have otherwise I'll just refactor it with an mu-plugin.

**Pull request merged**
