### PR TITLE
Add DashboardPageSpeedLoading component..

### PR DESCRIPTION
**Pull request by techanvil**
## Summary

This is a duplicate of the PR #6122 by @asvinb and @sashadoes which was accidentally merged, when it should have been moved to MR for an additional merge review from @felixarntz and @marrrmarrr, as per the AC.

However I also made a minor fix to one of the test descriptions: dd78be38b16ec017a9e6310ac0903b76bcc55419.

Addresses issue:

- #5776 

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [x] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [x] Ensure CI checks pass.
- [x] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Comment by techanvil** [comment]
I can't approve a PR I created (see **Summary** above), so just going to comment here and move to MR.

LGTM, nice one @asvinb & @sashadoes!

Moving to MR for additional merge review from @felixarntz and @marrrmarrr.

**Review by felixarntz — APPROVED** [review]
Thanks @techanvil, this looks great to me.

**Comment by felixarntz** [comment]
@marrrmarrr Can you please check the result of this PR as well for whether the loading UI looks good to you? You can easily review it here: https://google.github.io/site-kit-wp/storybook/pull/6168/?path=/story/pagespeed-insights-module-components--dashboard-widget-loading

**Review by aaemnnosttv — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
