### PR TITLE
Bug/2734 adsense summary widget

### PR DESCRIPTION
**Pull request by eugene-manuilov**
## Summary

Addresses issue #2734 

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
Looks good to me! This issue was missing a QA brief so I added one.

**Review by felixarntz — CHANGES_REQUESTED** [review]
The production code here looks good, but the related Storybook story is now broken, since the provided data from before no longer applies.

Screen Shot 2021-02-17 at 4 02 09 PM

Can you update the Storybook data accordingly?

**Comment by eugene-manuilov** [comment]
@felixarntz it should be fixed now.

**Review by felixarntz — APPROVED** [review]
Awesome!

**Pull request merged**
