### PR TITLE
Enhancement/7580-update-answer-based-metrics-for-news

### PR DESCRIPTION
**Pull request by jimmymadon**
## Summary

Addresses issue:

- #7580

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [x] Ensure the PR has the correct target branch.
- [x] Double-check that the PR is okay to be merged.
- [x] Ensure the corresponding issue has a ZenHub release assigned.
- [x] Add a changelog message to the issue.

### CODE REVIEW

**Review by hussain-t — APPROVED** [review]
Thanks, @jimmymadon. LGTM 👍

**Review by techanvil — APPROVED** [review]
LGTM!

**Review by techanvil — CHANGES_REQUESTED** [review]
Hi @jimmymadon, I hit approve on this one and then noticed it has a merge conflict. Please can you resolve it?

**Comment by techanvil** [comment]
This issue ran into a GitHub glitch when merging - it's merged successfully but the PR didn't update properly. @jimmymadon has confirmed the issue working as expected on `develop` and has closed the PR, I'm now deleting the branch.

**Comment by techanvil** [comment]
Oh right, how odd! Thanks for clarifying, @jimmymadon. There's some spooky GitHub business going on here... When's Halloween again? :smile:

**Pull request closed without merging**
