### PR TITLE
chore: Remove PHP Cron tasks

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue #667.

## Relevant technical choices

I left in the cron registration function in case we want to use it going forward, as the IB simply mentioned removing existing code. If it's best to just remove the file entirely I can, but I figured this would work fine 🤷‍♂ 

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by aaemnnosttv** [comment]
@googlebot I consent.

**Comment by tofumatt** [comment]
Fair enough; I've deleted the class 😄

**Comment by tofumatt** [comment]
He didn't, and ah: I see. I've reverted the commit. 👍

**Comment by aaemnnosttv** [comment]
@tofumatt you had one last failing test due to a method you removed on our test module class.

It's worth mentioning that the `Deactivation` class is related to plugin deactivation, which is different than _module_ deactivation 😄 

All the tests are passing now, so this should be good to go 👍

**Comment by tofumatt** [comment]
Ah, cheers. Trying to run these tests locally for me fails actually, so I kept trialing on Travis 😢

Thanks for the fix!

**Pull request merged**
