### PR TITLE
Introduce our own legend for Pie Charts in All Traffic widget.

### PR DESCRIPTION
**Pull request by asvinb**
## Summary

Addresses issue #2700 

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by asvinb** [comment]
The PR needs to be updated now that #2710 has been merged where we need to remove the negative margins introduced here: https://github.com/google/site-kit-wp/pull/2754/files#diff-9c02e442264b614408ff5c987b2652e3470828705cdd0aab2c36f4dc854bfd81R88
The negative margins were added because of the legend which was part of the Chart. Now that the legend is living outside of the chart, we no longer need the negative margins to reposition the placeholder.

**Review by aaemnnosttv — CHANGES_REQUESTED** [review]
Thanks @asvinb – this looks great!

A few things to address here:
1. I'm not sure if we want the global button focus style applied here (@felixarntz?)   
image
2. There is a slight shift when "activating" one of the items due to the change in font-weight  
Kapture 2021-02-04 at 19 37 48
3. I'm not sure exactly what the hover style should be here. The clip above shows an underline but this isn't present in the design. Also it isn't clear if the background color is supposed to be applied on hover as well or only on selection
4. You mentioned we shouldn't need the negative margins that were added in #2710 anymore to account for the legend from the charts – can we remove those styles that are no longer relevant?

I realize some of these things require answers that I don't have yet, but we should still address them here if we can.

**Comment by asvinb** [comment]
> Thanks @asvinb – this looks great!
> 
> A few things to address here:
> 
> 1. I'm not sure if we want the global button focus style applied here (@felixarntz?)
>    image
> 2. There is a slight shift when "activating" one of the items due to the change in font-weight
>    Kapture 2021-02-04 at 19 37 48
> 3. I'm not sure exactly what the hover style should be here. The clip above shows an underline but this isn't present in the design. Also it isn't clear if the background color is supposed to be applied on hover as well or only on selection
> 4. You mentioned we shouldn't need the negative margins that were added in #2710 anymore to account for the legend from the charts – can we remove those styles that are no longer relevant?
> 
> I realize some of these things require answers that I don't have yet, but we should still address them here if we can.

@aaemnnosttv My notes below
1. I would leave them mainly for accessibility reasons.
2. This is as per the designs where the active item has a font weight of 500.
3. I would leave the hover style as is else we'll need to find a way on how to style the hover state efficiently. Because right now, the colors are all set via inline CSS, which uses the same colors defined in the component. https://github.com/google/site-kit-wp/pull/2752/files#diff-3f30def21f83e2a53e6b645675570d834e6aa59efd4e4b2598d50b15543feaceR299 We can either add predefined classes in the CSS, thus duplicating the colors, or dynamically inject the hover styles via JS.
4. Yes, I'll remove the styles.

**Comment by asvinb** [comment]
@aaemnnosttv Negative margins have been removed.

**Comment by aaemnnosttv** [comment]
>> I'm not sure if we want the global button focus style applied here

> I would leave them mainly for accessibility reasons.

@asvinb  Sure, but this should be a deliberate decision though as it's a user-facing change, so we'll need input from @felixarntz about it.

>> There is a slight shift when "activating" one of the items due to the change in font-weight

> This is as per the designs where the active item has a font weight of 500.

Yes, I understand. The font weight is fine, but we should be able to [tweak the styles to prevent the shifting](https://css-tricks.com/bold-on-hover-without-the-layout-shift/) that this causes.

> I would leave the hover style as is else we'll need to find a way on how to style the hover state efficiently. Because right now, the colors are all set via inline CSS, which uses the same colors defined in the component. We can either add predefined classes in the CSS, thus duplicating the colors, or dynamically inject the hover styles via JS.

Looking at the markup there, we should be able to do this with CSS alone. We simply need to render the `span.googlesitekit-widget--analyticsAllTraffic__active-underlay` unconditionally (rather than only when `isActive`). Then in CSS, we just need to do something like this:
```scss
.googlesitekit-widget--analyticsAllTraffic__active,
.googlesitekit-widget--analyticsAllTraffic__legend-slice:hover {
    > .googlesitekit-widget--analyticsAllTraffic__active-underlay { display: block; }
}
```

Or, since the underlay is a separate element, could hide it with `opacity: 0` by default instead and vary this to create a better hover experience.

```scss
.googlesitekit-widget--analyticsAllTraffic__active-underlay {
    opacity: 0;
}
.googlesitekit-widget--analyticsAllTraffic__legend-slice:hover  .googlesitekit-widget--analyticsAllTraffic__active-underlay {
    opacity: .7;
}
.googlesitekit-widget--analyticsAllTraffic__active .googlesitekit-widget--analyticsAllTraffic__active-underlay {
    opacity: 1;
}
```
What do you think? There seems to be some room for improvement with the class names as well.
* `googlesitekit-widget--analyticsAllTraffic__active-underlay` should probably be:  
`googlesitekit-widget--analyticsAllTraffic__underlay` since it shouldn't really be active-only I think.
* `googlesitekit-widget--analyticsAllTraffic__active` should probably be:  
`googlesitekit-widget--analyticsAllTraffic__legend-slice--active` to match its main class.
Aside – shouldn't the `--` after `googlesitekit-widget` be a single dash, or underscore(s) since double dash usually indicates state? I guess we're not doing strict BEM here but would be good to maintain consistency where we can.

> Negative margins have been removed.

Awesome, thanks!

**Comment by asvinb** [comment]
@aaemnnosttv Thanks for the layout shift tip. I didn't know about that. :) Hover state has been added. About the class names, ideally they should have been in the following format: `googlesitekit-widget__xxx--yy` but to keep things consistent in the file, I used the same "convention"

**Comment by felixarntz** [comment]
@asvinb @aaemnnosttv We should fully stick to the Figma design for the hover, focus and active styles. Specifically:
* The legend entries should never be underlined.
* The legend entries should never have that outline.

I agree though that having hover, focus, and active all look the same is not a great idea. Maybe we could use the bolder font-weight only when active?

Regarding the slight shift, we should try to fix that while maintaining the bold font-weight as per the design.

**Comment by aaemnnosttv** [comment]
> I agree though that having hover, focus, and active all look the same is not a great idea. Maybe we could use the bolder font-weight only when active?

If by "active" you mean selected, that is how it is now:
image
- Direct `:hover`
- Organic Search: **selected** + `:focus`

> Regarding the slight shift, we should try to fix that while maintaining the bold font-weight as per the design.

That has already been fixed 😄

**Review by felixarntz — CHANGES_REQUESTED** [review]
@asvinb Can you remove the underline on hover and the outline on focus? Afterwards, this should be good to go.

**Comment by asvinb** [comment]
@aaemnnosttv @felixarntz Hover and focus styles removed. I also tweaked the code so that the "Others" legend is not clickable.

**Review by aaemnnosttv — APPROVED** [review]
Great, thanks @asvinb !

**Pull request merged**
