### PR TITLE
Fix / 4589 All Traffic Pie Slice Unselected On Click Outside - V2

### PR DESCRIPTION
**Pull request by 10upsimon**
## PLEASE NOTE
- This is a continuation of https://github.com/google/site-kit-wp/pull/7161 due to the double click bug not being addressed int he GA4 `UserDimensionsPieChart` component and only in the non-GA4 `UserDimensionsPieChart` component.

## Summary

Addresses issue:

- #4589

## Relevant technical choices

The following changes were effected in both the `UserDimensionsPieChart` components for GA4 specifically:

- Updated the `onExitClick()` function to make sure that the element checked in the `! event?.target?.closest` condition was less strict, and allowed clicking inside of the chart component without closing the tooltip. This also solves the prior reported "double click" bug, where segments would need clicking twice before activating and triggering data state change. This is inline with how it was fixed in the previous PR at https://github.com/google/site-kit-wp/pull/7161

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by tofumatt — CHANGES_REQUESTED** [review]
The technical notes here and the issue comment mentioning this is a continuation of another PR with changes for the GA4 widget seem… longer than this PR 😆 

Is this one line all that's needed for this change to work on GA4?

Totally fine if so, but just a bit surprised, like something's missing in here. The technical changes in this PR description made me expect a lot more 😅

**Comment by 10upsimon** [comment]
@tofumatt this is probably my bad, as I had copied the overview from the prior PR. I will update it now.

**Comment by 10upsimon** [comment]
@tofumatt I've update the **_Relevant technical choices_** section to be less (and unnecessarily) verbose.

**Review by techanvil — APPROVED** [review]
LGTM!

**Comment by techanvil** [comment]
Ah, I've just noticed the request for a review from @tofumatt.

@10upsimon, this being the case, the thing to do would be to assign the related issue to Matt in CR as well.

However, with this being a pretty small and straightforward PR that I've now approved, I will go ahead and merge it :)

**Comment by 10upsimon** [comment]
> the thing to do would be to assign the related issue back to Matt in CR as well.

Thanks @techanvil and my apologies for that, I'll keep that in mind for future issues, thank you!

**Review by tofumatt — APPROVED** [review]
All good, thanks all! 🙂

**Pull request merged**
