### PR TITLE
Don't use AMD parser for node_modules scripts.

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue #1141.

Fixes issue with lodash declaring a global (#1141).

Also removes unneeded lodash npm modules from package.json.

## Relevant technical choices

Rather than change to using `lodash-es`, this should protect us from other modules that tend to declare globals when imported using the AMD parser. My testing of this change didn't affect the site (which makes sense, all of our parsing/imports are not done using AMD style modules), and this rule was already in place in our own code.

It wasn't enforced for files in the `node_modules` folder as we wanted to exclude them from our babel transforms, but it can be safely enforced. All E2E tests also pass with this change, and it removes the `_` global from pages with Site Kit loaded 😄

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by aaemnnosttv** [comment]
Isn't this what this was added for? 🤔 
https://github.com/google/site-kit-wp/blob/5a23f5e15ede36cdb6990ae981f4546f524f6e6d/webpack.config.js#L107
Do we need both?

You mentioned e2e tests pass, but should we not also include the same rule in that bundle as well for consistency?

Should we maybe extract some common elements to variables to make the separate bundles more composable?

**Comment by tofumatt** [comment]
The IB in #1141 and the PR description, but the issue with that change is it doesn’t affect code in `node_modules`, as they’re excluded from the files webpack targets with those rules.

I suppose we can actually _remove_ the old rule for clarity, but it was never affecting lodash because it comes from an excluded folder for those rules.

**Comment by tofumatt** [comment]
Oh, whoops, I misread.

Yeah, adding that to all JS bundles makes sense. I’ll make the change 👍🏻

**Comment by aaemnnosttv** [comment]
@tofumatt I was thinking `module.rules` for JS could be extracted to a single variable/import, (not just the one rule) since this appears to be the same. What do you think?

**Comment by tofumatt** [comment]
Huh, right, good call! I've updated them to share the same ruleset. 👍

**Pull request merged**
