### PR TITLE
Enhancement/1326 gulp to webpack

### PR DESCRIPTION
**Pull request by eugene-manuilov**
## Summary

Addresses issue #1326 

## Relevant technical choices

* This PR pins @wordpress/data package version to just `4.12.0` (instead of `^4.12.0`) to prevent unexpected upgrade to the latest version.
* It turns out that we don't need to mess with webpack config to process images and svg files, it can be done using regular cli commands provided by appropriate packages.
* Release command has been rewritten to be a bash script because it's mainly used in the GitHub Actions where we use Linux. It lets us to get rid of more dependencies and not to deal with self-written nodejs scripts.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by eugene-manuilov** [comment]
@felixarntz @aaemnnosttv I need your opinion for this before I jump into revamping everything here. I worked on it in the scope of IB directives for this ticket which clearly define that `node`/`npm` approach for assets and a shell script for release are valid approaches:

> * Convert all tasks in ... to use webpack or **node/npm directly**. This should have no/little impact on the scripts we run, but they shouldn't rely on gulp anymore.
> * The release task looks like the most involved one/the task without an obvious Webpack replacement (Imagemin and SVG manipulation should be straightforward): ..., but converting that to either **a shell script** or a node+git library script should be straightforward.

I have already spent estimated time for this ticket and making additional changes will result in exceeding the limit. So need your evaluation whether this approach is sufficient or not.

Moving it webpack is nice but it is not necessary because there is little benefit in it. Furthermore it will require us to increase complexity of our webpack config, bring more dev dependencies and rework javascript files to import images in JS/SVG files directly into javascript using es6 which doesn't look nice in my opinion. Plus, additional benefit of the current approach in this PR is that it doesn't introduce changes in actual javascript files thus don't affect functionality itself.

Thanks in advance.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv / @tofumatt how do you want to process images with webpack loaded from PHP?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov can you give an example? I can't think of a case where we render an image outside of React 🤔

**Comment by eugene-manuilov** [comment]
@aaemnnosttv 

https://github.com/google/site-kit-wp/blob/897c92e479c3577ceceb3355b8c58c5c7287c4e3/includes/Core/Admin/Screen.php#L126-L133

https://github.com/google/site-kit-wp/blob/897c92e479c3577ceceb3355b8c58c5c7287c4e3/includes/Modules/AdSense.php#L539-L551

**Comment by aaemnnosttv** [comment]
Thanks @eugene-manuilov - I think that should ideally be replaced with a vector rather than a `png` - we could maybe even use https://developer.wordpress.org/resource/dashicons/#googleplus since `$icon_url` supports a Dashicon class name which looks identical at first glance 😄 
Otherwise, we could use one of the other two routes available to [`add_menu_page`](https://developer.wordpress.org/reference/functions/add_menu_page/)
> * Pass a base64-encoded SVG using a data URI, which will be colored to match the color scheme. This should begin with 'data:image/svg+xml;base64,'.
> * Pass 'none' to leave div.wp-menu-image empty so an icon can be added via CSS.

Any of these I think would be an improvement over the static image used currently.

Are there any other cases to consider?

**Comment by eugene-manuilov** [comment]
> Any of these I think would be an improvement over the static image used currently.

Can you tell me which one of those you want me to do? Just don't want to rework it again.

> Are there any other cases to consider?

There is one more, but that one is easier.

**Comment by aaemnnosttv** [comment]
> Can you tell me which one of those you want me to do? Just don't want to rework it again.

Sure @eugene-manuilov, using the base64-encoded SVG using a data URI seems like the best option. The only thing I'm not 100% sure about is if this is supported in WP 4.7. Let's check that and if it is, let's go with that. Otherwise, let's go with the CSS option which we've used in other places as well in a similar way: https://github.com/google/site-kit-wp/blob/897c92e479c3577ceceb3355b8c58c5c7287c4e3/assets/sass/components/global/_googlesitekit-text-field-icon.scss#L23

**Comment by eugene-manuilov** [comment]
@aaemnnosttv @tofumatt what do you think about SVG? Currently, we merge all svg files into a single big svg file full of sprites and load that file. If we want to use webpack, we will need to load svg files separately, right? How do you think we should migrate it into webpack?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov Unless @tofumatt has any other ideas or suggestions, I think we can use [`@svgr/webpack`](https://www.npmjs.com/package/@svgr/webpack) which is what `create-react-app` uses. It gives you a named `ReactComponent` for each `svg` you import and is pretty nice in my experience. See https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

**Comment by eugene-manuilov** [comment]
> I think we can use @svgr/webpack which is what create-react-app uses. 

@aaemnnosttv it will require to rework all occurrences of the SvgIcon component to load svg files directly instead of using the sprite. Is it okay?

**Comment by aaemnnosttv** [comment]
@eugene-manuilov at first glance it seems like there are a fair number of these that would need replacing (~42) although in most cases this looks like a straightforward replacement and some of them will obviously be duplicates. There are a few instances however where the svg `id` to show is dynamic where there would be a little more to rework (e.g. `PageHeader` and `moduleIcon` in `assets/js/util/index.js`). Given that most of them seem easy, I'm still in favor of this change in general.  I can definitely help figure out the way forward with the ones that aren't straightforward though. Perhaps we should create a new issue just for these SVG changes as a prerequisite to finishing this one since this touches a bit more than just build configuration? Let's talk about it on our call shortly.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov as discussed, I'm creating a new issue for the svg related work now which will need to be done before this issue can be finished. It should be ready for definition soon.

**Comment by eugene-manuilov** [comment]
Going to close this PR in favor of https://github.com/google/site-kit-wp/pull/2159

**Pull request closed without merging**
