### PR TITLE
E2E: Site Kit Dashboard Tests | Dashboard Search

### PR DESCRIPTION
**Pull request by aaemnnosttv**
## Summary

Addresses issue #265 

## Relevant technical choices

* Adds a few posts to the env install script for testing

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by swissspidy** [comment]
@aaemnnosttv Wouldn't it make sense if this also addressed #431 by adding a post with special characters? I don't see any test for that issue.

**Comment by aaemnnosttv** [comment]
@swissspidy it wasn't part of the AC, but I can add one 👍

**Comment by swissspidy** [comment]
Moving back to "In Progress" nonetheless as I think the ACs from #431 also apply here.

**Comment by aaemnnosttv** [comment]
Added a test for posts with special characters 👍

**Pull request merged**
