### PR TITLE
TagManager Datapoint Refactoring

### PR DESCRIPTION
**Pull request by aaemnnosttv**
## Summary

Addresses issue #452

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by aaemnnosttv** [comment]
This will require datacache to be regenerated before the build will pass.

**Comment by felixarntz** [comment]
@aaemnnosttv 
> This will require datacache to be regenerated before the build will pass.

Does it actually? The datapoints are only used during setup/settings, so I don't believe there is an overlap with the storybook data. The builds also pass already as such.

**Comment by aaemnnosttv** [comment]
> Does it actually?

I guess not! 😄 I thought it would but the build says otherwise 👍 Must be that VRT doesn't cover this module yet?

**Comment by felixarntz** [comment]
@aaemnnosttv I think it's only relevant for those VRTs that rely on `googlesitekit.admin` or particularly prefilled request data for `googlesitekit.admin.datacache`, the latter of which mostly concerns data views. I think we don't have much VRT coverage for individual module setup/settings.

**Pull request merged**
