### PR TITLE
Bug/5183 adsense api account status

### PR DESCRIPTION
**Pull request by eugene-manuilov**
## Summary

Addresses issue:

- #5183

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by tofumatt — CHANGES_REQUESTED** [review]
I followed the QA steps here but when following this step in the QA brief I didn't see the dropdown:

> Set the tester plugin AdSense account status to "multiple". Go to the AdSense setup. You should now see the dropdown to select an account. If you land in another situation (where your account seems as if it was already selected), it would mean the problem was not fixed as expected.

When I follow those steps I see this screen:

CleanShot 2022-05-11 at 16 27 45

Here are my settings in the tester plugin:

CleanShot 2022-05-11 at 16 24 45

The other QA steps seem to work fine though.

**Comment by felixarntz** [comment]
@tofumatt Two follow-up question on your QA feedback here:
1. Are you using the latest version of the tester plugin? We recently added a small follow-up fix to it so that the accounts response in case of no accounts is indeed an empty array instead of an error, which is crucial for QAing this one.
2. Did you also perform the previous step to go through the setup flow with account status set to `none` before? That is crucial because that should reset the `accountID` to be empty. If the `accountID` is set to one of the accounts from the `multiple` accounts, it bypasses the dropdown to select the account.

**Comment by tofumatt** [comment]
@felixarntz Ah, I didn't have 1.8.2 of the tester plugin, that totally fixed it! I followed the steps you outlined but I didn't have the latest one.

Thanks! 👍🏻

**Review by tofumatt — APPROVED** [review]
Tested with the new tester plugin (1.8.2) and it worked a treat. I'll add that requirement to the QA Brief and then merge this 👍🏻

**Pull request merged**
