### PR TITLE
Decouple Tag Manager from Analytics

### PR DESCRIPTION
**Pull request by aaemnnosttv**
## Summary

Addresses issue #2096

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by felixarntz — CHANGES_REQUESTED** [review]
There's one minor UX flaw here that we should fix: When first setting up Tag Manager with a container that has an Analytics property, and then continuing to the Analytics setup from there, the error that there is a conflicting Analytics property will briefly flash up (for a split second):
Screenshot 2020-10-07 at 17 01 44 (2)

This is likely because at the end of the flow we activate the Analytics module, and of course then the initially set up property won't match. It shouldn't even get to displaying anything like that in the Tag Manager flow though and instead stay "navigating" until the user gets to the Analytics setup.

**Comment by aaemnnosttv** [comment]
@googlebot I consent.

**Comment by aaemnnosttv** [comment]
@felixarntz the previous UX issue is good now, the only remaining issue is the reauthURL not requesting the added scopes.

**Comment by felixarntz** [comment]
@aaemnnosttv The problem with the reauth URL was indeed with timing:
* Module activation triggers a refresh of the user authentication data, which includes required scopes and comparing to the user's available scopes.
* This data is a dependency to the module's reauth URL, which will therefore generally be updated accordingly, _however_: Because the URL is retrieved at the root of the component in a `useSelect`, at the time of executing the callback it is in the state of before the module activation. **It needs to be fresh from right after module activation instead.**
* For this kind of required behavior, it makes sense to provide the data from the action response so that the callback can use it. This can be accomplished with a registry control that selects the data.

See https://github.com/google/site-kit-wp/pull/2140/commits/42d4babeae82a11213e56cc426c91f8272aeb838.

**Review by felixarntz — APPROVED** [review]

**Pull request merged**
