### PR TITLE
Feature/3525 organise svg assets

### PR DESCRIPTION
**Pull request by ivankruchkoff**
## Summary

Addresses issue #3525

## Relevant technical choices

* idea-hub-notification.svg has multiple colours so I moved it to /graphics/ in the one change from the IB.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
Looks good to me! All SVG assets are in the `assets/svg` folder and the plugin still seems to function properly to me. 👍🏻

**Comment by tofumatt** [comment]
(I've pushed a fix for the merge conflicts; if all tests pass this is good-to-go.)

**Review by aaemnnosttv — CHANGES_REQUESTED** [review]
@tofumatt VRT is failing with difference where it's really hard to tell what changed, maybe the color is slightly different? Let's double check that and either fix the difference or update the reference image here.

https://user-images.githubusercontent.com/1621608/148565916-3fc26faa-59e8-4a82-b61b-787310df7da5.mp4

**Comment by aaemnnosttv** [comment]
Looks like the color used in the `warning.svg` changed from the inline fill of `#F9BB2D` to use our `$c-warning -> $c-selective-yellow` (`#fbbc05`) in https://github.com/google/site-kit-wp/commit/4da329c2b2552f308495fec4279ca906074be4be. The two are undecipherable to my eyes, but they're apparently 5% different according to [this tool](https://htmlcolors.com/hex-to-hsl) 
image

This is fine as there is no real visual difference and we're changing it to use a color from our set of colors in CSS so this is an improvement and we can go ahead and update the reference image accordingly, which I've updated.

I'm also pushing a fix for the nav icons which were under the `graphics` directory when they belong under icons instead.

**Pull request merged**
