### PR TITLE
E2E Setup & Authorization Flow | Admin 2

### PR DESCRIPTION
**Pull request by aaemnnosttv**
## Summary

Addresses issue #221 

## Relevant technical choices

* Adds a `logoutUser` utility to address instability around changing users
* Refactors a few other tests to benefit from added utilities

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by swissspidy** [comment]
I still don't experience these instability issues locally, the test passes just fine without using `logoutUser` at all.

**Comment by aaemnnosttv** [comment]
@swissspidy the most recent build failed, but not on all jobs.
Here's the failure https://travis-ci.com/google/site-kit-wp/jobs/225840405

I know what you mean about not seeing the problem with loginUser - I didn't see it before either, but there seems to be an element of randomness to it, which is eliminated by logging out first.

I believe this failure is related to that. Looks like it's been restarted now but it was timing out while waiting for `'.googlesitekit-splash-intro button'` which would happen if the user didn't change since the previous user was already set up. When the login fails due to the typing slip up in the browser, the utility doesn't do anything to ensure that the login was successful (e.g. navigated to dashboard, etc) probably because you can be redirected anywhere after logging in so that would be difficult/impossible. When the test fails because of this, it is hard to reason about why because the previous user is still logged in so it can resume navigating to other pages, etc.  

I think we should keep the user of `logoutUser` to ensure this doesn't happen. It's also closer to what a real user would do.

**Comment by swissspidy** [comment]
@aaemnnosttv Was that failure specific to WordPress 4.7?

**Comment by aaemnnosttv** [comment]
I've run it a few times locally, including with WP `4.7.13` and it's passing.

**Comment by swissspidy** [comment]
`tests/e2e/specs/auth-flow-admin-2.test.js` passes just fine locally and on Travis.

On Travis, `tests/e2e/specs/auth-flow-editor.test.js` failed on WP 4.7. I forgot to remove the `logoutUser` part there, which I just did now.

Let's see how that works. If it's not reliable we can revert my changes again. And ideally investigate the root cause of these hiccups 🙂

**Comment by aaemnnosttv** [comment]
WP 4.7 build is still failing in the same place. Strange that it's only on 4.7 though.

https://travis-ci.com/google/site-kit-wp/builds/123531214

**Comment by swissspidy** [comment]
Weirdly enough the 4.7 tests worked just find for me locally 🤔

**Pull request merged**
