### PR TITLE
Change all component definitions to use `function` over "arrow" style declarations

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue:

- #3513

## Relevant technical choices

For unnamed functions, `function-expression` was required because unnamed functions don't support the `function-declaration` style, which makes sense I guess. 😄 

These can be auto-fixed by ESLint so any errors in the future should be auto-fixed by developers with VSCode auto-fix enabled 👍🏻 

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by aaemnnosttv — COMMENTED** [review]
@tofumatt glad we were able to resolve the issue with it not working initially 👍 

What do you think about amending the rule to ignore stories and tests? It seems like a lot of the changes in here are in these files and I wouldn't be opposed to allowing more flexibility there.

**Comment by aaemnnosttv** [comment]
> I figure it's best to just apply it everywhere, especially as it'll auto-fix so developers don't really need to think about it that way.

SGTM, thanks.

---

Looks like something is broken with Backstop still
https://github.com/google/site-kit-wp/actions/runs/7090760177/job/19304262528?pr=7952#step:5:275

**Comment by tofumatt** [comment]
Oh, weird, right on. Thanks, I figured it was just a CI glitch.

Turns out it's an AST thing—because the function definitions changed from `const foo = () => {};` to `function foo() {}` it changed slightly how the [AST parser/code](https://github.com/google/site-kit-wp/blob/639a27c5d7a2eeaed97b675361d7ab950696736c/tests/backstop/scenarios.js#L81-L85) handles stuff.

The fix was straightforward, just needed to check that the object exists 🙂

**Review by aaemnnosttv — APPROVED** [review]
:shipit:

**Pull request merged**
