### PR TITLE
Make enough room for y-axis labels on small screens.

### PR DESCRIPTION
**Pull request by asvinb**
## Summary

Addresses issue #2095 

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by aaemnnosttv** [comment]
@asvinb E2E and VRT are failing, can you take a look?

**Comment by aaemnnosttv** [comment]
@asvinb it looks like the VRT change will require the reference images approved/updated. The E2E looks like an odd fluke network failure. 

Checking locally, I don't see the numbers cut off like you had shown before, although on very small viewports (iPhone 5) it truncates the x-axis (as well as plot) labels 😭  – I think this is out of scope of this issue and probably low impact.

| iphone 5 | iphone 6/7/8 |
| --- | --- |
| image | image |

Please review the VRT diff to make sure nothing unexpected is happening there and then we can approve that. I'm guessing E2E will pass when run again, so don't worry about that much just yet.

**Comment by aaemnnosttv** [comment]
@googlebot I consent.

**Review by aaemnnosttv — APPROVED** [review]
LGTM 👍

**Review by felixarntz — APPROVED** [review]
Great!

**Pull request merged**
