### PR TITLE
Enhancement/2727 preview block

### PR DESCRIPTION
**Pull request by asvinb**
## Summary

Addresses issue #2727 

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by eugene-manuilov — APPROVED** [review]
From the technical point of view, everything looks okay. However, the selected approach seems to be excessive and goes beyond what has been requested in the AC. 

I don't think we need to introduce new hooks and a new dependency to implement responsive preview blocks. We can use `window.matchMedia()` to check breakpoints and it will do the trick. The only benefit of the new hook is that it listens to the `onresize` event on our behalf, but I am not convinced that it's really needed. Even though if we really needed it, it will be better to implement the `onresize` event listener in the component itself instead of bringing in a new dependency. Fewer dependencies we use are better for us.

I am going to approve it and leave the final decision to @aaemnnosttv or @felixarntz.

**Comment by aaemnnosttv** [comment]
Thoughts @tofumatt? You suggested the added package that @asvinb added per the IB, but @eugene-manuilov feels it may not be necessary. What do you think?

**Review by tofumatt — APPROVED** [review]
My instinct is that especially for code like this, where the dependency is not a large API surface area or likely to change much—it does one thing and does it well—we're better off using an external dependency over maintaining the code ourselves. There's less code we need to write and test, less logic for more mundane things like this, etc.

I can see both arguments, but in this case the additional dependency doesn't create upgrade difficulties or anything. Changes like Styled Components, a UI component, or even some sort of Redux middleware introduce issues. But in this case—it's a small amount of code we don't have to maintain, and were we to write this code ourselves I think we'd do it exactly the same as the hook.

It's a useful feature to have in the code so I'd rather it be reusable than not.

So my take is that we include the dependency. 🙂

**Comment by aaemnnosttv** [comment]
@googlebot I consent.

**Review by aaemnnosttv — APPROVED** [review]

**Pull request merged**
