### PR TITLE
Replace STORE_NAME usage with named constants (3599).

### PR DESCRIPTION
**Pull request by johnPhillips**
## Summary

Addresses issue #3599

## Relevant technical choices

For `create-X-store.js` files and tests, there are still properties/internal variables with `STORE_NAME` values—these are separate and since they're part of the API not worth changing here. They're also internal and don't cause the confusion 

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by tofumatt** [comment]
@googlebot I consent.

**Review by eugene-manuilov — CHANGES_REQUESTED** [review]
Thanks, @johnPhillips and @tofumatt. This looks good, however there are one issue in the e2e tests. Could you please take a look at it?

**Comment by tofumatt** [comment]
The fixtures here didn't change at all, but now we're seeing an E2E error with this change being required cd9b615878f47c730075558a08a18b632db74901.

It fixes the error and seems harmless, but I don't know why it's required now. 🤷🏻‍♂️

**Review by eugene-manuilov — APPROVED** [review]
LGTM

**Pull request merged**
