### PR TITLE
Fix the lack of spacing in IP anonymization settings.

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue #18.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by felixarntz** [comment]
@tofumatt Can you fix the VRT images accordingly?

**Comment by tofumatt** [comment]
Just doing that—I mean to push them right after creating the PR but they seem to be getting stuck on my Mac. Going to try to clean the build and re-generate them again...

**Comment by tofumatt** [comment]
VRTs updated, sorry 'bout the delay on that one! 😅

**Comment by tofumatt** [comment]
Not sure why that test didn't get added! All good, now, hopefully 😓

**Pull request merged**
