### PR TITLE
Update to open feedback cta links in a new tab.

### PR DESCRIPTION
**Pull request by Hazlitte**
## Summary

Update to open feedback cta links in a new tab.

Addresses issue #3510 

## Checklist

- [X] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [X] I have added a QA Brief on the issue linked above.
- [X] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by Hazlitte** [comment]
@tofumatt Thanks for explaining the underlying logic for this in the other PR.  I created a new PR from main fir this due to the release.

**Comment by tofumatt** [comment]
Since that issue wasn't tagged with the release it's fine to target `develop`, and for future reference we can change the branch to merge into without creating a new PR, so in the future please don't close existing PRs—if the issue was tagged with the release feel free to change the branch, but in this case it was fine to keep it on `develop`.

**Review by tofumatt — APPROVED** [review]
Looks good 👍🏻

**Comment by Hazlitte** [comment]
Ok, thanks @tofumatt 👍

**Pull request merged**
