### PR TITLE
Fix consent mode Ads connection status logic

### PR DESCRIPTION
**Pull request by nfmohit**
## Summary

Addresses issue:

- https://github.com/google/site-kit-wp/issues/8365#issuecomment-2058749960

## Relevant technical choices

This PR fixes [this issue](https://github.com/google/site-kit-wp/issues/8365#issuecomment-2058749960) by not requiring both Ads and Analytics modules to be connected for the Ads connection status.

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Comment by nfmohit** [comment]
**Note to Code Reviewer:** Updates to the VRT references were needed because the `provideModules` utility function automatically sets the `Ads` module as connected. We'd have to go into each story and make it appear disconnected, which felt a little unnatural, but please let me know if I should do that instead.

**Comment by techanvil** [comment]
> **Note to Code Reviewer:** [Updates to the VRT references](https://github.com/google/site-kit-wp/pull/8568/commits/b6800604b3bbd8aa341a4da2732b4e2cbfa81cbf) were needed because the `provideModules` utility function automatically sets the `Ads` module as connected. We'd have to go into each story and make it appear disconnected, which felt a little unnatural, but please let me know if I should do that instead.

Thanks @nfmohit. Considering how the `SettingsCardConsentMode` stories have an explicit `WithAdsConnected` variant, it doesn't seem appropriate to keep Ads connected for the other variants. I've pushed a change to address this myself to save the round trip.

image

**Comment by nfmohit** [comment]
> > **Note to Code Reviewer:** [Updates to the VRT references](https://github.com/google/site-kit-wp/pull/8568/commits/b6800604b3bbd8aa341a4da2732b4e2cbfa81cbf) were needed because the `provideModules` utility function automatically sets the `Ads` module as connected. We'd have to go into each story and make it appear disconnected, which felt a little unnatural, but please let me know if I should do that instead.
> 
> Thanks @nfmohit. Considering how the `SettingsCardConsentMode` stories have an explicit `WithAdsConnected` variant, it doesn't seem appropriate to keep Ads connected for the other variants. I've pushed a change to address this myself to save the round trip.
> 
> image

Sounds fair, thank you @techanvil!

**Review by techanvil — APPROVED** [review]
LGTM, nice one @nfmohit!

**Pull request merged**
