### PR TITLE
Infrastructure/6185 - Fix the VRT tests that are failing in CI

### PR DESCRIPTION
**Pull request by hussain-t**
## Summary

Addresses issue:

- #6185 

## Relevant technical choices

- A few more stories had to be fixed than the ones mentioned in the IB.
- We had to delay the VRT scenarios for certain stories.

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Comment by hussain-t** [comment]
@asvinb, the fonts are Google fonts loaded from external sources, so we need the delay. However, I have reduced it to one second (`1000`). I don't think it's good to delay the global, though; that would greatly slow the test run down.

**Comment by asvinb** [comment]
Actually @hussain-t my question was more about needing the delay for specific stories compared to all stories. Technically the Google fonts are used everywhere, that's why I was thinking about the global delay, compared to delays in specific stories.

**Comment by hussain-t** [comment]
@asvinb, I'm not sure why it's necessary for some stories. As I mentioned, the fonts are Google fonts loaded from external sources, so it probably has something to do with that. IMO, it's better to scope the delay with the specific stories instead of having it global; otherwise, it would slow down the tests. However, if you think it's better to have it globally, we can tackle it in a separate ticket.

**Comment by asvinb** [comment]
Thanks @hussain-t !LGTM!

**Review by techanvil — APPROVED** [review]
LGTM, nice one @hussain-t!

**Pull request merged**
