### PR TITLE
Update "Dashboard view" string in Analytics settings.

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue:

- #6931

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by aaemnnosttv — CHANGES_REQUESTED** [review]
Thanks @tofumatt – this is almost there, we also need to update this in the non-edit view of the settings.

image

See https://google.github.io/site-kit-wp/storybook/pull/7012/?path=/story/modules-analytics-settings-settingsview--with-dashboard-view

**Comment by tofumatt** [comment]
That's odd, I made the change here: https://github.com/google/site-kit-wp/pull/7012/files#diff-8288a7c1bc54d93872341dd5b2e65fed3fba481ea2cef9a025d5160e2ef41ee1R123

It's in the updated VRT images as well, though looks like there was a font change and they need to be updated again to avoid a merge conflict.

I'll make the change, but can you check that you didn't test in a cached version/the wrong branch? The changes are all made 🤔

**Comment by aaemnnosttv** [comment]
The PR only shows the one line changed in `SettingsForm`, and all the VRT updates show the edit view.

We also need to update it in the settings view here `assets/js/modules/analytics/components/settings/SettingsView.js` 👍

**Review by aaemnnosttv — APPROVED** [review]
Thanks @tofumatt ! I pushed the last change there as it was just as simple as the other, + updated the affected VRT images 👍

:shipit:

**Pull request merged**
