### PR TITLE
Extract Bundlesize to its own job/check

### PR DESCRIPTION
**Pull request by benbowler**
Extract Bundlesize to its own job/check.

## Summary

Addresses issue #2539

## Relevant technical choices

I followed [these documents](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) to get the head commit message and SHA.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by benbowler** [comment]
If the context is incorrect we can check is using this action step:

```
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```

**Comment by aaemnnosttv** [comment]
The request to report the check is failing it seems:
https://github.com/google/site-kit-wp/runs/1761296111?check_suite_focus=true#step:9:16

Not sure what's going on exactly but it's resulting in a 500 Internal server error.

**Comment by benbowler** [comment]
Hey @aaemnnosttv, I have done some rearch, including following [this thread](https://github.com/siddharthkp/bundlesize/issues/308). As we don't have control over the Vercel (now.sh) set up I wasn't able to dig into why this is returning a 500 error. 

There is a more actively maintained alternative called [bundlewatch](https://github.com/bundlewatch/bundlewatch) with more active commits and a similar web service to https://bundlesize-store.now.sh.

Would you consider switching?

**Comment by aaemnnosttv** [comment]
Thanks @benbowler – it looks like this is working which is great! However one thing I noticed as a feature on the `compressed-size-action` which is something we'll definitely want to use is the `strip-hash` option. This is really important for our use since the hash will change any time the resulting file changes which would undermine the whole process of comparing the size from one version to another since without this it would always see them as separate files.

This should be fairly straight forward to add, again because the action offers support for this, we just need to configure it to match our hashes so they can be stripped.

See https://github.com/preactjs/compressed-size-action#dealing-with-hashed-filenames

**Review by felixarntz — APPROVED** [review]
Great!

**Pull request merged**
