### PR TITLE
Fix Other radio/checkbox getting disabled for text input with trailing spaces

### PR DESCRIPTION
**Pull request by felixarntz**
## Summary

Addresses issue #2897 (follow-up to #2950)

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by tofumatt — DISMISSED** [review]
Tested locally and it worked great, looks good 👍🏻

**Comment by aaemnnosttv** [comment]
Updating the target branch to `master` since #2950 is already merged for the release.

**Comment by aaemnnosttv** [comment]
Going to try to retrigger all the actions with a close+reopen since they all show skipped.
image

**Review by aaemnnosttv — APPROVED** [review]
LGTM!

**Pull request merged**
