### PR TITLE
Fix GA4 AdSense linked notification dismissal logic.

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue:

- #8238

## Relevant technical choices

Fixed the logic for checking whether the notification should be dismissed or not. Also tidied up the dismissal key name.

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by 10upsimon — APPROVED** [review]
This LGTM thanks @tofumatt and test suite is passing, moving this along to merge review.

**Review by 10upsimon — COMMENTED** [review]
Actually @tofumatt I just realized VRT is failing, checking if this is due to pipeline error or not.

**Comment by 10upsimon** [comment]
@tofumatt I am just waiting for VRT test to re-run as there was a pipeline error. Will re-review thereafter.

**Review by 10upsimon — APPROVED** [review]
Re-approving after re-run of VRT tests, thanks @tofumatt

**Review by kuasha420 — APPROVED** [review]
Thanks @tofumatt. PT LGTM, the failing E2E is unrelated.

**Pull request merged**
