### PR TITLE
Enhancement/3058 help icon needs circular mouse hover

### PR DESCRIPTION
**Pull request by danielgent**
## Summary

Addresses issue #3058

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

**Before**
header-before

**After**
header-after

### CODE REVIEW

**Comment by danielgent** [comment]
Do check out the visual diff change! In storybook the flag `helpVisibility` is not set

Screenshot from 2021-04-14 15-23-01

**Comment by tofumatt** [comment]
@googlebot I consent.

**Review by tofumatt — CHANGES_REQUESTED** [review]
First off: I added a new story to this PR because we didn't have a header like one on most dashboard views—with both the Help Menu and the Date Range selector: 687315bf462c02f5a90ce0181509bd07b0cd59ac

You can view the story here: https://google.github.io/site-kit-wp/storybook/pull/3143/?path=/story/global--plugin-header-with-help-menu-and-date-range-selector

The spacing looks nice on larger viewports, but unfortunately on mobile this design gets very cramped. On a very large mobile it works _okay_, save for an odd hover effect, but note what happens when a smaller viewport is used:



This is what it looks like on an iPhone X:

Screenshot 2021-04-15 at 01 26 03

-----

This might be an issue with the IB itself—I'm not sure if mobile viewports were taken into account. But further design work might need to be done to allow for the proposed spacing in the header.

**Comment by asvinb** [comment]
@googlebot I consent.

**Review by tofumatt — CHANGES_REQUESTED** [review]
This still has issues with not only iPhone SE sizes (`320px` wide) but also iPhone X sizes:

#### iPhone SE

Screenshot 2021-04-15 at 21 00 52

#### iPhone X

Screenshot 2021-04-15 at 21 00 45

You can see this at https://google.github.io/site-kit-wp/storybook/pull/3143/iframe.html?id=global--plugin-header-with-help-menu-and-date-range-selector&viewMode=story using a mobile viewport.

So I think the spacing still needs adjusting.

**Comment by asvinb** [comment]
@tofumatt In Storybook, there is 50px padding on each side, meaning that the content area is further reduced. If you're testing on iPhone 5, the content area in Storybook is not 320px but only 220px. Can you test within WordPress itself instead of Storybook? This is how it should look:
image

I think to avoid any confusion in the further, we need to revisit the "small mobile" viewport option in Storybook so that the content area is actually 320px, not including the extra padding from Storybook.

**Comment by tofumatt** [comment]
@asvinb Oh, shoot, I didn't realise that! I've filed #3174 to address that issue, thanks!

I'll test in the WP dashboard instead. 👍🏻

**Review by tofumatt — APPROVED** [review]
Looks great now:

Screenshot 2021-04-16 at 15 02 33

Thanks 👍🏻

**Review by tofumatt — APPROVED** [review]
(Pushed the latest `develop` to fix the E2E Nightly test failure.)

**Pull request merged**
