### PR TITLE
Replace deprecated node-sass with dart-sass

### PR DESCRIPTION
**Pull request by aaemnnosttv**
## Summary

Addresses issue #2561 

* https://github.com/sass/node-sass
* https://webpack.js.org/loaders/sass-loader/#getting-started

Performance impact (running `npm run dev`)

**Before**
```
✔ Basic Modules
  Compiled successfully in 15.59s

✔ Module Entry Points
  Compiled successfully in 31.19s

✔ Plugin CSS
  Compiled successfully in 34.18s

✔ Test files
  Compiled successfully in 15.43s
```

**After**
```
✔ Basic Modules
  Compiled successfully in 11.71s

✔ Module Entry Points
  Compiled successfully in 26.27s

✔ Plugin CSS
  Compiled successfully in 28.93s

✔ Test files
  Compiled successfully in 11.67s
```

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by aaemnnosttv** [comment]
VRT is failing here with some minor differences 🤔  will take a closer look after the holidays.

image

**Review by eugene-manuilov — CHANGES_REQUESTED** [review]
@aaemnnosttv we also need to update the wepback config in the storybook folder:

https://github.com/google/site-kit-wp/blob/68d07d368da86e7b93b9201176cf5fba1af2fb0d/.storybook/webpack.config.js#L55-L63

**Comment by benbowler** [comment]
@aaemnnosttv I've taken a closer look here, running diffs on the output files from develop vs this branch and I've tracked down why the visual regression tests were failing. It turned out that dart-sass calculates fractional variables to a higher number of decimal places that node-sass did:

Screenshot 2021-01-19 at 13 41 54

There are several cases where this happens in letter-spacing and some in 1/3 % widths in the grid system. As this is "more accurate" I've approved the VRT changes in this branch.

**Review by eugene-manuilov — APPROVED** [review]
LGTM!

**Comment by benbowler** [comment]
@googlebot I consent.

**Comment by aaemnnosttv** [comment]
Thanks @benbowler ! I can't technically approve the PR since it started out as my own, but CR ✅

**Pull request merged**
