### PR TITLE
Adjust user input wording.

### PR DESCRIPTION
**Pull request by adamsilverstein**
## Summary

Related issue: https://github.com/google/site-kit-wp/issues/2790

This PR makes a slight language change for the user input flow confirmation message. 

The previous message caused some confusion when being translated and this change helps clarify the string.

cc: @marrrmarrr please confirm I got the wording right.

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by adamsilverstein** [comment]
@felixarntz This is a tiny, string only change: should I create a matching issue to work thru the board regardless?

**Comment by adamsilverstein** [comment]
I noticed the VRT failing here. Running the tests to check, three images are changed due to the string change, but two of the images failed to load data correctly. Going to rebuild and try again.

**Review by felixarntz — APPROVED** [review]
Great!

**Comment by adamsilverstein** [comment]
I could use some help here getting the VRTs to pass. When I run the tests locally, I see the expected changes where I changed the string, but also some unexpected/unrelated changes.

**Comment by adamsilverstein** [comment]
Test results:
image

**Review by felixarntz — APPROVED** [review]
@adamsilverstein Not sure what was going on there - happened for me once too, but then it worked. I've updated the VRT references.

**Pull request merged**
