### PR TITLE
Fix AdSense snippet default

### PR DESCRIPTION
**Pull request by aaemnnosttv**
## Summary

Addresses issue #556 

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by swissspidy** [comment]
@aaemnnosttv `Google\Site_Kit\Tests\Modules\AdSenseTest::test_register` is failing now.

**Comment by aaemnnosttv** [comment]
@swissspidy Yeah, sorry. I'm working on that now.

**Comment by aaemnnosttv** [comment]
@swissspidy tests are all fixed up now - it should be good to go.

**Comment by swissspidy** [comment]
@aaemnnosttv @felixarntz The visual regression tests on `develop` seem to failing after this merge: https://travis-ci.com/google/site-kit-wp/builds/128475265

**Pull request merged**
