### PR TITLE
Update bundled WP used for tests

### PR DESCRIPTION
**Pull request by aaemnnosttv**
## Summary

Addresses issue:

- #6290 

## Relevant technical choices

None

Tests all run locally 👍 

```
⚡  composer test                                                                       
> phpunit
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

...............................................................  63 / 947 (  6%)
............................................................... 126 / 947 ( 13%)
........................................SS..................... 189 / 947 ( 19%)
............................................................... 252 / 947 ( 26%)
............................................................... 315 / 947 ( 33%)
............................................................... 378 / 947 ( 39%)
............................................................... 441 / 947 ( 46%)
......SSS...................................................... 504 / 947 ( 53%)
............................................................... 567 / 947 ( 59%)
............................................................... 630 / 947 ( 66%)
............................................................... 693 / 947 ( 73%)
............................................................... 756 / 947 ( 79%)
............................................................... 819 / 947 ( 86%)
............................................................... 882 / 947 ( 93%)
............................................................... 945 / 947 ( 99%)
..                                                              947 / 947 (100%)

Time: 35.32 seconds, Memory: 64.50MB

OK, but incomplete, skipped, or risky tests!
Tests: 947, Assertions: 3506, Skipped: 5.
```

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [x] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [x] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [x] Ensure the PR has the correct target branch.
- [x] Double-check that the PR is okay to be merged.
- [x] Ensure the corresponding issue has a ZenHub release assigned.
- [x] Add a changelog message to the issue.

### CODE REVIEW

**Review by techanvil — APPROVED** [review]
LGTM, nice one @aaemnnosttv!

**Review by techanvil — CHANGES_REQUESTED** [review]
Apologies, I was a bit trigger-happy on the review, I didn't spot that a conflict has emerged in `composer.lock`. Please resolve the conflict, and this should be good to go!

**Comment by aaemnnosttv** [comment]
Thanks, I had to re-commit the changes because there were some weird problems resolving the merge conflict. Should be good now!

**Comment by aaemnnosttv** [comment]
I've merged a few more issues and now this is conflicting again 😄 ...

**Review by techanvil — APPROVED** [review]
LGTM, nice one @aaemnnosttv

**Pull request merged**
