### PR TITLE
Show generic error message when Search Console request is forbidden.

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue:

- #4543

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by hussain-t — COMMENTED** [review]
@tofumatt The changes LGTM 👍 

However, when I tested on my local, I can see the expected error message only for Search Console. `Analytics Gathering Data` CTA is rendered for Analytics.

Screenshot 2022-02-24 at 5 23 00 PM

**Comment by tofumatt** [comment]
Good catch @hussain-t 👍🏻 

Note: for a site that's gathering data, if you DELETE it (and thus lose access), only some of the errors appear:

CleanShot 2022-02-24 at 23 49 26

But other parts are stuck in the "loading" state. Seems like maybe the checks for what to render are running in an odd order. I'll take a look at this further 👍🏻

**Comment by hussain-t** [comment]
Thanks @tofumatt 👍

**Comment by hussain-t** [comment]
Thanks @tofumatt.
>Looks like those components had the error condition below the loading condition

This makes sense. However, after pulling your changes I do get the same behaviour on my end 🤔

**Comment by tofumatt** [comment]
On the non-unified Dashboard, which is what this issue primarily addresses, yes, it works. I see this:

CleanShot 2022-03-07 at 21 19 36

But this is what appears on the Unified Dashboard:

CleanShot 2022-03-07 at 21 21 48

Admittedly that's not exactly what the issue was about, but I've updated it so it shows this now:

CleanShot 2022-03-07 at 21 23 20

**Review by hussain-t — APPROVED** [review]
Thanks @tofumatt. LGTM 👍

**Review by eugene-manuilov — APPROVED** [review]
LGTM

**Pull request merged**
