### PR TITLE
Update TwG Post Type chip design

### PR DESCRIPTION
**Pull request by nfmohit**
## Summary

Addresses issue:

- #5754 

## Relevant technical choices

This PR updates the design of the TwG Post Type chips to match the Figma designs and to be consistent with the Dashboard Sharing UserRoleSelect.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by tofumatt — CHANGES_REQUESTED** [review]
Looks good and I like the consolidation of the `Chip` component! 👍🏻 

On the Thanks with Google screen everything looks good and functions as-expected, including keyboard navigation:

CleanShot 2022-09-13 at 01 57 25

But on the Dashboard Sharing modal, _any_ keyboard input (including tabbing to the next item), activates the chip, which looks like a bug/regression. Here's a recording including keyboard inputs:

CleanShot 2022-09-13 at 01 56 07

Once the Dashboard Sharing regression is fixed this should be good-to-go 👍🏻

**Review by tofumatt — CHANGES_REQUESTED** [review]
There's still an issue here with keyboard navigation, but only when the "Edit Roles" button is activated and then the "All" Chip is focused.

I think the issue stems from changing `onKeyDown` to `onKeyUp`, because it seems like the "All" Chip is receiving the "key up" event that's fired after "Return" is "key up"'d.

Back when the chips detected key down this was fine, so I think that might be the change that's causing this behaviour?

Here's a screenshot with key presses:

CleanShot 2022-09-13 at 23 51 20

----

We should make sure that the new `Chip` component doesn't require us to guard against this kind of behaviour in general; when focus changes because of a change of layout on the page and the newly-focused element (that is a `Chip`) is what receives the `keyUp` event. It'd probably be best to revert that change… I get the intention, but it's probably better to just handle the key down to prevent bugs like this.

**Comment by nfmohit** [comment]
Great catch, thank you @tofumatt!

I've removed this limitation in the `<Chip />` component and reverted to using `keyDown` for `UserRoleSelect`.

**Review by tofumatt — APPROVED** [review]
Thanks so much for the work on this, looks and works great now! 👍🏻

**Pull request merged**
