### PR TITLE
Remove top-level puppeteer dependency

### PR DESCRIPTION
**Pull request by aaemnnosttv**
## Summary

Addresses issue #1797 

## Relevant technical choices

* Did not include changes to package-lock here as they were irrelevant

```diff
diff --git a/package-lock.json b/package-lock.json
index 30d1e45fa..90af30ed8 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -12395,6 +12395,11 @@
           "resolved": "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.2.1.tgz",
           "integrity": "sha512-vkcDPrRZo1QZLbn5RLGPpg/WmIQ65qoWWhcGKf/b5eplkkarX0m9z8ppCat4mlOqUsWpyNuYgO3VRyrYHSzX5g=="
         },
+        "prettier": {
+          "version": "npm:wp-prettier@2.0.5",
+          "resolved": "https://registry.npmjs.org/wp-prettier/-/wp-prettier-2.0.5.tgz",
+          "integrity": "sha512-5GCgdeevIXwR3cW4Qj5XWC5MO1iSCz8+IPn0mMw6awAt/PBiey8yyO7MhePRsaMqghJAhg6Q3QLYWSnUHWkG6A=="
+        },
         "puppeteer": {
           "version": "npm:puppeteer-core@3.0.0",
           "resolved": "https://registry.npmjs.org/puppeteer-core/-/puppeteer-core-3.0.0.tgz",
@@ -30836,11 +30841,6 @@
       "resolved": "https://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz",
       "integrity": "sha1-1PRWKwzjaW5BrFLQ4ALlemNdxtw="
     },
-    "prettier": {
-      "version": "npm:wp-prettier@2.0.5",
-      "resolved": "https://registry.npmjs.org/wp-prettier/-/wp-prettier-2.0.5.tgz",
-      "integrity": "sha512-5GCgdeevIXwR3cW4Qj5XWC5MO1iSCz8+IPn0mMw6awAt/PBiey8yyO7MhePRsaMqghJAhg6Q3QLYWSnUHWkG6A=="
-    },
     "prettier-linter-helpers": {
       "version": "1.0.0",
       "resolved": "https://registry.npmjs.org/prettier-linter-helpers/-/prettier-linter-helpers-1.0.0.tgz",
@@ -33170,7 +33170,7 @@
         },
         "strip-ansi": {
           "version": "3.0.1",
-          "resolved": "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz",
+          "resolved": "http://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz",
           "integrity": "sha1-ajhfuIU9lS1f8F0Oiq+UJ43GPc8=",
           "dev": true,
           "requires": {
@@ -39594,7 +39594,7 @@
       "dependencies": {
         "strip-ansi": {
           "version": "3.0.1",
-          "resolved": "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz",
+          "resolved": "http://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz",
           "integrity": "sha1-ajhfuIU9lS1f8F0Oiq+UJ43GPc8=",
           "dev": true,
           "requires": {
```

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by eugene-manuilov — CHANGES_REQUESTED** [review]
Looks good to me. However `package-lock.json` has to be committed as well even though changes in it seem to be not needed. Could you please add it to your PR?

**Comment by aaemnnosttv** [comment]
> However `package-lock.json` has to be committed as well even though changes in it seem to be not needed. 

@eugene-manuilov I would have thought that removing it would have resulted in some change that references `puppeteer` but it isn't referenced at all and I get the exact same changes in my lock file just from running `npm install` on the current develop branch. Why commit these changes if it doesn't change the lock file in a meaningful way? Just curious if there is some other reason or significance to changing the lock file that isn't obvious here.

**Comment by aaemnnosttv** [comment]
@eugene-manuilov lock file updated 👍

**Review by eugene-manuilov — APPROVED** [review]
Looks good to me.

**Pull request merged**
