### PR TITLE
Update eslint configuration

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue #217.

This PR updates the ESLint configuration to be in-line with the WordPress JS lint rules (`plugin:@wordpress/eslint-plugin/recommended`).

## Relevant technical choices

This PR does not make extensive overrides to the default config or ignore rules. The only exceptions are:

1. two `// eslint-disable-next-line @wordpress/no-unused-vars-before-return` because of what seems like an eslint bug with component variables being inside the return value.
2. Converting JSDoc errors to be a warning rather than an error.
3. Allowing `wp` global usage.

On the second point: there are a large number of JSDoc rule violations (over 70) that require a bit of code knowledge/context I'm thus far lacking, but they would also take up a lot of time to document. I wasn't sure if that's useful—is there a plan to use JSDoc for public APIs offered by the library? Or would it be useful/are we currently generating JSDoc pages for internal development use? If so I can convert that back to an error, or we could even file a follow-up issue to prevent this one from getting too wild 😄

On the third point: I think it's worth getting away from the `wp` global usage, but in a separate PR might be nicer, as this is already quite a large and difficult-to-review changeset, full of very minor changes. (See: https://github.com/google/site-kit-wp/issues/217#issuecomment-523358259 for context.)

---

### Update
* Eslint has been upgraded to v6.1.0  
The latest version 6.2.0 and 6.2.1 have known issues with some `for ... of` and related loops so it's been pinned on this earlier version for compatibility.
* `@babel/traverse` has been added to the root dependencies.  
This resolves a very strange bug that happened when switching eslint packages which caused eslint to fail when parsing template strings. See babel/babel-eslint#530
* The webpack config has been updated for compatibility with eslint v6 where `eslint-loader` is used.  
See https://github.com/webpack-contrib/eslint-loader/issues/238#issuecomment-505672107

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards. 😄
- [x] My code has proper inline documentation.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by tofumatt** [comment]
@googlebot I signed it!

(Sorry about that, I had signed one on behalf of my organisation but it seems not to have taken. I've signed an individual one for now!)

**Comment by aaemnnosttv** [comment]
@googlebot I consent.

**Comment by swissspidy** [comment]
Hmm could the QUnit tests be run through Babel? Or could we just switch to Jest? 🙃

**Comment by tofumatt** [comment]
I think the plan should definitely to switch them over to Jest, but I thought it was out-of-scope for this PR. 😄

Given that, I wasn't sure about running them through Babel, but I could spend a few minutes seeing if it's trivial. Given we'll replace them with Jest tests though, I figured it was best to leave them alone.

**Comment by tofumatt** [comment]
Hmm, strangely, it seems they _should_ be run through Babel (as there's other stuff in here that is failing to run in an ES5 environment), but something changed. Having a look now...

**Comment by swissspidy** [comment]
Yay, build passing at last 🎉 

Checking now!

**Comment by swissspidy** [comment]
Two main things I saw:

* Some obsolete leftovers that could be removed
* `.storybook` folder was unnecessarily ignored  
  While `.storybook/data` can be ignored, it's reasonable to expect that the config files adhere to the coding standards

**Pull request merged**
