### PR TITLE
Update translators comments for single placeholders.

### PR DESCRIPTION
**Pull request by sashadoes**
## Summary

Addresses issue:

- #5924 

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by hussain-t — CHANGES_REQUESTED** [review]
Thanks, @sashadoes. The PHP side of single placeholders isn't fixed. Plus please take a pull from the latest `develop`. It will have some new files, for example, `WPVersionBumpNotification`.

**Review by hussain-t — APPROVED** [review]
Thanks, @sashadoes LGTM!

**Review by tofumatt — CHANGES_REQUESTED** [review]
Looks like a few more comments need updating based on the ACs/IB:

* https://github.com/google/site-kit-wp/blob/626ea8db5a33a76e2d1c002b96b51a44bbad1cf4/google-site-kit.php#L48
* https://github.com/google/site-kit-wp/blob/626ea8db5a33a76e2d1c002b96b51a44bbad1cf4/includes/Core/Admin/Screens.php#L385
* https://github.com/google/site-kit-wp/blob/626ea8db5a33a76e2d1c002b96b51a44bbad1cf4/includes/Core/Authentication/Authentication.php#L1134
* https://github.com/google/site-kit-wp/blob/626ea8db5a33a76e2d1c002b96b51a44bbad1cf4/includes/Core/Authentication/Authentication.php#L1139
* https://github.com/google/site-kit-wp/blob/626ea8db5a33a76e2d1c002b96b51a44bbad1cf4/includes/Core/Authentication/Setup.php#L179
* https://github.com/google/site-kit-wp/blob/626ea8db5a33a76e2d1c002b96b51a44bbad1cf4/includes/Core/Authentication/Clients/OAuth_Client_Base.php#L311

Actually, it looks like a lot of `*.php` files are missing the change, so it's worth looking through PHP files to make sure all of the single-placeholder translation comments are replaced there.

**Review by tofumatt — APPROVED** [review]
Oops, looks like a VSCode issue had me check out this branch but not get the updates in it? Dunno, but now it's all fine!

Thanks for letting me know I forgot how to use git @sashadoes 😅

**Pull request merged**
