### PR TITLE
Remove Dashboard View change and UA Dashboard View components.

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue:

- #6786

## Relevant technical choices

I opted not to remove the `isGA4DashboardView` selector itself but hardcode it to `true`, just to cut down on PR size since it's not explicitly in the ACs, but I can add that to this one if needed.

This removes all Dashboard View settings in PHP/JS and the UI to switch between the settings and to view it. The Dashboard view is now always GA4.

There are a few Storybook stories that still reference UA, which I thought was helpful as part of this PR to confirm the change, but that could ultimately be removed in this PR if desired. But otherwise they're fine to remove during the `ga4Reporting` feature flag removal.

-----

From what I can see this satisfies all the ACs and works well in my testing—it might even go a bit beyond the ACs, but I figured removing as much code where straightforward is good. Let me know if you'd like less or more removed 😆 

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [x] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [x] Ensure CI checks pass.
- [x] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [x] Ensure the PR has the correct target branch.
- [x] Double-check that the PR is okay to be merged.
- [x] Ensure the corresponding issue has a ZenHub release assigned.
- [x] Add a changelog message to the issue.

### CODE REVIEW

**Review by techanvil — CHANGES_REQUESTED** [review]
Hey @tofumatt, nice work here so far. There are, though, a couple of points from the IB that have been missed:

> - Remove the `New` badges added to indicate new GA4 metrics.
> - The Analytics module SettingsView should be restructured following [this Figma screen](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=562-8638&t=BPBoEvLnYHLMIYxY-0).

As per my separate comment, it looks like we can also remove the remaining usage of `GA4_DASHBOARD_VIEW_NOTIFICATION_ID`.

Thanks for the additional info in **Relevant technical choices** - from what I can see, keeping `isGA4DashboardView()` makes sense for now as we still do rely on its remaining logic, although arguably it should be renamed. We've still got plenty more tidying up and removing of UA features to come though, so I think it can happily wait for another issue, and from what I can see the remaining stories you mentioned can too.

**Comment by tofumatt** [comment]
Thanks @techanvil! Changes made and removed those new badges, so this should be good-to-go now 👍🏻

**Review by techanvil — CHANGES_REQUESTED** [review]
Thanks @tofumatt - however this one point from the IB is still technically outstanding (specifically, it's initial sub-point):

> - The Analytics module `SettingsView` should be restructured following [this Figma screen](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=562-8638&t=BPBoEvLnYHLMIYxY-0).
>   - In `assets/js/modules/analytics/components/settings/SettingsView.js`:
>     - Add a new setting meta item at the first position before all other settings, labelled `Account`, which should display the account ID. This can be copied over from `assets/js/modules/analytics/components/settings/GA4SettingsView.js`.

I do realise it doesn't directly correlate to the AC, but it has been specced - having said that you did approve the IB, so if you feel it's out of scope here, I'd be happy to skip this part. What do you think?

**Comment by tofumatt** [comment]
Oh, right, I meant to cover that here in the technical notes.

We have a separate issue for that here: #6821. I think I meant to mention it in my IB Review and totally forgot 🤦🏻

I think we should omit it from this issue though. It's pretty unrelated and as discussed in that IB might warrant a new selector, etc., so we should do that separately.

**Comment by tofumatt** [comment]
> I've noticed there are a few VRT tests that need to be fixed - once these are done, I think this will be good to go.

Ah, cheers, I thought that was just a timeout. I've fixed it, now is good-to-go 😄

**Review by techanvil — CHANGES_REQUESTED** [review]
Hey @tofumatt, thanks for updating the VRT tests. Sorry to have to send this back again, I had thought it would indeed be good to go. However, I've noticed that you've removed some tests as part of your recent merge of `develop` into this branch - see [this diff](https://github.com/google/site-kit-wp/pull/7581/files/d5f5ff508f75647bc15f1e901fc34d1b009b5f0a..fc8c6799eec465fb4ea94b5266d6aad01de4e089).

The thing is, the logic these test cases are testing still exists in the codebase - it's part of the recently merged PR https://github.com/google/site-kit-wp/pull/7590.

So, unless we're also removing this logic here - which I think would be out of scope, and I don't feel entirely confident it would be safe to do so just yet, it would need a good bit of unpicking to check if these cases are not longer reachable - I think we should keep the tests too. It looks like they'd need a bit of a tweak to use an alternative way to modify the return value of `isGA4DashboardView()`, with the explicit `dashboardView` setting out of the picture, but beyond that I think they are good to keep. What do you think?

**Comment by tofumatt** [comment]
Sure thing, I'll make the changes to those tests/logic and restore them 👍🏻

**Pull request merged**
