### PR TITLE
Enhancement/3250 transitional setup form

### PR DESCRIPTION
**Pull request by eugene-manuilov**
## Summary

Addresses issue #3250 

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by eugene-manuilov** [comment]
@googlebot I consent.

**Comment by danielgent** [comment]
@googlebot I consent.

**Review by tofumatt — CHANGES_REQUESTED** [review]
The existing code and stories here look good, but it looks like part of the IB is missing:

> * The title should be different based on the result from the  `getPrimaryPropertyType` selector.
>     * If it's `ua`, the title should be: `You'll need to connect the Google Analytics 4 property that's associated with this Universal Analytics property`,
>     * else it should be: `You'll need to connect the Universal Analytics property that's associated with this Google Analytics 4 property`.
> * The dropdowns in the blue are rendered conditionally based on the primary property (via the `getPrimaryPropertyType` selector):
>     * If it's `ua`, use the `PropertySelect` component from the `modules/analytics-4` module.
>     * If it's `ga4`, use the `PropertySelect` component from the `modules/analytics` module. The `ProfileSelect` component should also be displayed next tot he `PropertySelect` component. Refer to the `User selects GA4 property` flow in Figma.

I don't see any conditional rendering of the notice prop based on the type of Analytics Primary Property Type. Does that still need to be added?

**Comment by eugene-manuilov** [comment]
> The existing code and stories here look good, but it looks like part of the IB is missing:
> 
> > * The title should be different based on the result from the  `getPrimaryPropertyType` selector.
> >   
> >   * If it's `ua`, the title should be: `You'll need to connect the Google Analytics 4 property that's associated with this Universal Analytics property`,
> >   * else it should be: `You'll need to connect the Universal Analytics property that's associated with this Google Analytics 4 property`.
> > * The dropdowns in the blue are rendered conditionally based on the primary property (via the `getPrimaryPropertyType` selector):
> >   
> >   * If it's `ua`, use the `PropertySelect` component from the `modules/analytics-4` module.
> >   * If it's `ga4`, use the `PropertySelect` component from the `modules/analytics` module. The `ProfileSelect` component should also be displayed next tot he `PropertySelect` component. Refer to the `User selects GA4 property` flow in Figma.
> 
> I don't see any conditional rendering of the notice prop based on the type of Analytics Primary Property Type. Does that still need to be added?

Yes, this is needed. Thanks for catching it.

**Comment by tofumatt** [comment]
@googlebot I consent.

**Review by tofumatt — APPROVED** [review]
Looks good, thanks!

I think @johnPhillips might need to consent to his commits in the PR; I'll ping him to ask him to authorise it 🙂

**Pull request merged**
