### PR TITLE
Add max-width to GA4 notices (3540).

### PR DESCRIPTION
**Pull request by johnPhillips**
## Summary

Addresses issue #3540

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by tofumatt — CHANGES_REQUESTED** [review]
Looks good, but the VRTs are failing. Can you take a look?

**Comment by johnPhillips** [comment]
@tofumatt I don't _think_ they are anything to do with this PR.

I can't get them to fail locally on this branch, and it also seems to be down to changes in the AdSense module data. Have a look below. There are 3 failing images all doing this. What do you think?

| Reference | Test | Diff |
|---|---|---|
| ref | test | diff |

**Review by tofumatt — APPROVED** [review]
Oh right, these VRTs were failing elsewhere but I think are fixed in `develop`. I'll merge that in and see how it goes 😄

**Comment by tofumatt** [comment]
@googlebot I consent.

**Pull request merged**
