### PR TITLE
Migrate to eslint-webpack-plugin and quiet webpack output.

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue #2509.

## Relevant technical choices

This wasn't part of the original IB, but the webpack noise is currently _extremely_ high, and it makes it difficult to see things like ESLint errors, etc. I added:

```js
config.stats = 'errors-warnings';
```

to all of the webpack configs so they're quieter. We can back that out of the change if you like, but I thought it was useful.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by eugene-manuilov — CHANGES_REQUESTED** [review]
@tofumatt don't we need to add the eslint plugin to the storybook webpack config?

**Comment by tofumatt** [comment]
We weren't using `eslint-loader` in the old storybook config, and I don't think it's very useful since the tests/build would fail during a normal `npm run build` (or warn during `npm run watch`) anyway. I don't think we _also_ need to do it in Storybook as our `lint` task covers storybook files, so it mostly just adds extra time to storybook compiles.

But I removed the devserver bit as suggested 👍🏻

**Review by eugene-manuilov — DISMISSED** [review]
Awesome!

**Review by aaemnnosttv — CHANGES_REQUESTED** [review]
Thanks @tofumatt – this looks good but didn't work quite as expected in my testing.

Running a production build fails as expected with ESLint errors when present, however a development build (`dev` or `watch`) did not emit any error or warnings at all during the build or when rebuilding (during watch). I didn't test any ESLint warnings (I think we error on everything.. do we have anything that warns?). Currently ESLint errors do show in webpack output. A `dev` build will fail with ESLint errors (although I realize this PR changes that) but we should still see the errors. Similarly, a `watch` build won't fail but the errors are shown in the build output.

The less verbose output with webpack is nice though if we can keep that 👍

**Comment by tofumatt** [comment]
> Running a production build fails as expected with ESLint errors when present, however a development build (dev or watch) did not emit any error or warnings at all during the build or when rebuilding (during watch). I didn't test any ESLint warnings (I think we error on everything.. do we have anything that warns?).

This is the issue I mentioned during a previous call that I wasn't sure was related to this change or not. I guess maybe it is. It seems the errors are only omitted during the first webpack build/compliation—subsequent builds don't warn/error 😞

I'll look into it further, but there aren't any obvious config settings to enable the desired behaviour…

**Comment by tofumatt** [comment]
So I had a look and adding `failOnError` improves things, but it seems that still the errors sometimes don't show after saving. It's hard to pin down but seems to be when a file with errors is saved, then corrected, then saved again: the errors won't be output. I've no idea why that is, but adding `failOnError` seemed to improve output consistency.

That's all I've got though 😞

**Review by aaemnnosttv — APPROVED** [review]
Thanks @tofumatt – I found this worked well, showing the errors on rebuild when there was and it didn't break the build either. The more concise output is nice as well 👍

**Pull request merged**
