### PR TITLE
Make sure `window.google` is undefined before loading Charts.

### PR DESCRIPTION
**Pull request by kuasha420**
## Summary

Addresses issue #4074

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by aaemnnosttv** [comment]
Thanks @kuasha420, this looks great. If it's not too much effort, can we add a test for this as well as described in the IB? We don't need to render any specific charts that Site Kit uses, but we should ensure that a chart that renders after charts have already been loaded does not raise this error. We could use something simple as is shown in the [Quick Start](https://github.com/rakannimer/react-google-charts#quick-start).

**Comment by kuasha420** [comment]
@aaemnnosttv should I add a unit test for the component and/or a storybook test? 

Cheers!

**Comment by aaemnnosttv** [comment]
@kuasha420 just a component test should suffice as this is more of a timing issue. The visual state of the component is irrelevant. Thanks 👍

**Comment by kuasha420** [comment]
@aaemnnosttv Hi Evan, I don't think unit testing the loaded state of charts library is possible in jest/jsdom as the charts never load no matter how much I wait. I also found [this](https://github.com/rakannimer/react-google-charts/issues/214) which reaffirms the point. The two charts remain in loading state forever in Jest. As there is no way to see if the `undefined` error is happening with/without applying the fix in this PR via jest, is there any value in adding the test like this? I think not. 

```js
// GoogleChart.test.js
import { Fragment } from '@wordpress/element';
import GoogleChart from './GoogleChart';
import { render } from '../../../tests/js/test-utils';

describe( 'GoogleChart', () => {
	it( 'renders two consecutive google charts without throwing when there is a `div` with id `google` in dom', () => {
		const divGoogle = document.createElement( 'div' );
		divGoogle.id = 'google';
		document.body.appendChild( divGoogle );

		const { container } = render(
			<Fragment>
				<GoogleChart
					chartType="LineChart"
					data={ [
						[ 'Age', 'Weight' ],
						[ 4, 5.5 ],
						[ 8, 12 ],
					] }
					width="100%"
					height="400px"
					legendToggle
				/>
				<GoogleChart
					chartType="LineChart"
					data={ [
						[ 'Age', 'Weight' ],
						[ 4, 5.5 ],
						[ 8, 12 ],
					] }
					width="100%"
					height="400px"
					legendToggle
				/>
			</Fragment>
		);
		expect(
			container.querySelectorAll( '.googlesitekit-chart' ).length
		).toEqual( 2 );
	} );
} );
```

**Review by aaemnnosttv — APPROVED** [review]
Thanks @kuasha420 ! I was hoping we could have added a test but unfortunately that isn't going to work like you said. This works great though 👍

**Pull request merged**
