### PR TITLE
Fix mysql issues during GH Action runs.

### PR DESCRIPTION
**Pull request by eugene-manuilov**
## Summary

Addresses issue #3068

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Review by aaemnnosttv — COMMENTED** [review]
@eugene-manuilov – it looks like the changes here may only solve the problems we were seeing due to the delayed execution of mysql commands; we're not truly waiting for the service to be fully available/ready.

See the note under ["No connections until MySQL init completes"](https://hub.docker.com/_/mysql#:~:text=No%20connections%20until%20MySQL%20init%20completes) on Docker hub. Ideally, we'd wait for this (maybe we could extract a common helper for use with E2E as well?). As it is, we're still assuming it's ready, just checking later.

If this is too much effort right now, we can go with this and revisit if it comes up again.

**Comment by eugene-manuilov** [comment]
@aaemnnosttv I don't think we need to re-invent the wheel. GitHub Actions already do it for us:
github com_google_site-kit-wp_runs_2255462654_check_suite_focus=true

The runner waits till MySQL container is ready and only then starts executing our steps. Of course, we can use the following command instead of `mysqladmin ping`, but I think it is overkill and not really needed:

```sh-session
mysql -e "select 1" -u root -pwordpress > /dev/null 2>&1
```

**Comment by aaemnnosttv** [comment]
> The runner waits till MySQL container is ready and only then starts executing our steps.

Right, that's partly what I mean. GitHub Actions was already doing this before and we were still seeing connection errors.

Is there a difference between the service being "healthy" and ready to accept commands?

**Comment by eugene-manuilov** [comment]
> > The runner waits till MySQL container is ready and only then starts executing our steps.
> 
> Right, that's partly what I mean. GitHub Actions was already doing this before and we were still seeing connection errors.

Yes, I think you are right, GHA was doing it before and we were still seeing connection errors. :thinking:  

> Is there a difference between the service being "healthy" and ready to accept commands?

In our case, GHA uses what we put in `--health-cmd` argument: https://github.com/google/site-kit-wp/blob/05e1c2f9c856609f713bdf58e0d920a49a42199b/.github/workflows/php-tests-wp-latest-php-7-4.yml#L25

Looks like `phpadmin ping` doesn't guaranty that MySQL is ready to accept requests. If we want to be more precise, we can use MySQL command to execute `select 1` query as I posted above, but I still think that it is overkill and we don't need to change it.

**Comment by aaemnnosttv** [comment]
> Looks like `phpadmin ping` doesn't guaranty that MySQL is ready to accept requests. If we want to be more precise, we can use MySQL command to execute `select 1` query as I posted above, but I still think that it is overkill and we don't need to change it.

Okay, let's go with how it is for now and reassess if needed 👍

**Review by aaemnnosttv — APPROVED** [review]
👍

**Pull request merged**
