### PR TITLE
Fix/4822 - Functionalities fixes follow up

### PR DESCRIPTION
**Pull request by hussain-t**
## Summary

Addresses issue:

- #4822 

## Relevant technical choices

- This PR fixes the issues #3 and #14 [observed](https://github.com/google/site-kit-wp/issues/4822#issuecomment-1145073745) by @wpdarren 

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Review by tofumatt — CHANGES_REQUESTED** [review]
I left a question about this PR here: https://github.com/google/site-kit-wp/issues/4822#issuecomment-1147791507

But it's probably best to answer here in this PR…

---

In the comment you wrote:

> As for `#1` and `#9`, this is a backend issue that only the modules available in the `_googlesitekitDashboardSharingData.settings` are changeable. @jimmymadon should be able to provide more context on this as he worked on the backed part of it.

But I was thinking that in this case, we should not be showing UI for modules we can't change. Do you think those modules _should_ be editable? I'd think so, but maybe I'm not following.

Either they should be editable (preferred if they can be shared)… or if they totally can't be shared we shouldn't show them for now.

**Review by tofumatt — COMMENTED** [review]
Actually, it looks like the issues I mentioned have actually been fixed in another PR so this should be good-to-go 🙂

Just doing some more testing before approving, but thought I'd leave this update here 👍🏻

**Review by tofumatt — CHANGES_REQUESTED** [review]
Hmm, I expected these not to appear open after clicking "apply" (you mentioned it as fixed in the issue I think), but it's still happening to me:

CleanShot 2022-06-06 at 22 55 57

**Comment by hussain-t** [comment]
@tofumatt, please refer to this [comment](https://github.com/google/site-kit-wp/issues/4822#issuecomment-1148208511).

**Comment by tofumatt** [comment]
@hussain-t Sorry, I don't understand how that comment relates to the list of items appearing open after clicking "apply". I think there's a lot of cross-talk and issues being referred to there, can you explain why here they aren't being closed after clicking "Apply"?

**Comment by hussain-t** [comment]
@tofumatt, I was responsible for fixing issues 1,3,9, and 14. The issue you're referring to is 4 from the @wpdarren's list. That should be fixed in @asvinb's PR.
Screenshot 2022-06-07 at 5 39 30 PM

**Pull request merged**
