### PR TITLE
Update to fix help menu button bug.

### PR DESCRIPTION
**Pull request by Hazlitte**
## Summary

Update to fix help menu button bug.

Addresses issue #3026 

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [X] I have added a QA Brief on the issue linked above.
- [X] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by Hazlitte** [comment]
Hi @tofumatt, this PR includes the code for passing an `onSelected` function from the parent to the `Menu` component.  I looked at adding a default prop function to the `Menu` component as an alternative and didn't find a quick solution.  So I thought it would be best to solve the bug and then pass it over to you to have a look at the `Menu` component.

**Review by tofumatt — CHANGES_REQUESTED** [review]
Ohhh, I see, `menuOpen` is a prop that `Menu` takes, so internally closing the menu isn't great as the [`useEffect`](https://github.com/google/site-kit-wp/blob/111c6653e27da89ed30568ee425fcbc0d27036e7/assets/js/components/Menu.js#L67-L73) in the `Menu` component will override it.

We could change that by adjusting `Menu`'s props API to handle the `menuOpen` internally when the `menuOpen` prop isn't a boolean (so `undefined` would cause internal handling but `true`/`false` would cause prop-based handling), which is a _nicer_ API but out-of-scope of this issue.

And since the other menus already handle it, let's leave that alone for now. It could be nice as a follow-up, code quality issue but let's see if we need that before we do it 🙂 

----

In that case, this largely looks good, but it looks like one of the menu buttons doesn't have the `className` we're targeting (`.googlesitekit-header__dropdown `), so the outlines in the header look like this:



I think that `className` should be added to that date menu button as well, assuming no other adverse side effects, so they all get the new outline-less styling. After that this is good-to-go 👍🏻

**Comment by tofumatt** [comment]
@googlebot I consent.

**Review by tofumatt — APPROVED** [review]
Thanks, looks good 👍🏻

**Review by tofumatt — APPROVED** [review]

**Pull request merged**
