### PR TITLE
Check for undefined scopes in `DashboardMainApp`.

### PR DESCRIPTION
**Pull request by tofumatt**
## Summary

Addresses issue:

- #7981

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [x] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [x] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [x] Ensure the PR has the correct target branch.
- [x] Double-check that the PR is okay to be merged.
- [x] Ensure the corresponding issue has a ZenHub release assigned.
- [x] Add a changelog message to the issue.

### CODE REVIEW

**Review by zutigrm — APPROVED** [review]
Thanks @tofumatt LGTM. Couldn't reproduce the issue, and permission messages still work as intendned.

There is a VRT failure for text field, for which there is a discussion [here](https://10up.slack.com/archives/CBKKQEBR9/p1702987471574249). Not sure if we should approve failed images, or wait for the follow-up PR, from discussion, to be merged and sync with develop so it can be fixed here. I am leaving that as a queston for Merge Reviewer

**Review by techanvil — APPROVED** [review]
LGTM!

**Comment by techanvil** [comment]
VRT tests are failing but they are unrelated, and look like they will be fixed via https://github.com/google/site-kit-wp/pull/8003.

**Comment by techanvil** [comment]
> Thanks @tofumatt LGTM. Couldn't reproduce the issue, and permission messages still work as intendned.
> 
> There is a VRT failure for text field, for which there is a discussion [here](https://10up.slack.com/archives/CBKKQEBR9/p1702987471574249). Not sure if we should approve failed images, or wait for the follow-up PR, from discussion, to be merged and sync with develop so it can be fixed here. I am leaving that as a queston for Merge Reviewer

Thanks @zutigrm, with these failing VRT tests unrelated to the changes here and the fix underway, I have merged this issue.

**Pull request merged**
