### PR TITLE
Validate Composer configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
## Summary

Addresses issue #3409

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

### CODE REVIEW

**Comment by szepeviktor** [comment]
I do not have energy to reason on failure.

> require.google/apiclient-services : unbound version constraints (>=0.157) should be avoided

Please consider listening to Composer.

**Comment by felixarntz** [comment]
@szepeviktor I just tried to push to your branch to fix this, but it looks like I do not have access - I'm willing to fix this problem. Would you mind addressing it via your branch?
1. Change the version constraint to be `"google/apiclient-services": "^0.157"`.
2. Run `composer update google/apiclient-services`.
3. Commit the updated `composer.json` and `composer.lock` file.

**Comment by szepeviktor** [comment]
Dony-Done!

**Comment by szepeviktor** [comment]
BTW I think there are many more files in this repo without syntax/validity check.

**Review by felixarntz — APPROVED** [review]
Excellent, thanks!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
