### PR TITLE
Follow up PR: Update conversion tailored metrics.

### PR DESCRIPTION
**Pull request by benbowler**
## Summary

Addresses issue:

- #9437

## Relevant technical choices

I updated the displayed metrics based on the image in the ticket rather than the list in the design doc.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

### CODE REVIEW

**Comment by benbowler** [comment]
Note for @kelvinballoo during QA, the list of metrics for each survey setting should not match the image in the ticket:

Image

*Note: the KM_ANALYTICS_TOP_DEVICE_DRIVING_PURCHASES metrics is not yet implemented so when sell_products_or_service is selected there will only be 7 widgets shown.*

Also @zutigrm has confirmed in Slack that the order of the widgets shown in the Key Metrics section is not important as long as they are all there.

**Review by zutigrm — APPROVED** [review]
Thanks @benbowler LGTM

**Review by tofumatt — APPROVED** [review]

**Comment by tofumatt** [comment]
Test failures seem unrelated…

**Comment by techanvil** [comment]
> Test failures seem unrelated…

Hmm, actually the `assets/js/googlesitekit/datastore/user/key-metrics.test.js` failures do appear to be caused by the commit in this PR. I've sent the issue back to @benbowler for a followup fix.

**Comment by benbowler** [comment]
Thanks @techanvil, I've fixed these tests and we should get this through quickly to allow other developers to see more clearly if tests are passing.

**Comment by techanvil** [comment]
Thanks @benbowler, and agreed, I'll review that now to move it along.

**Pull request merged**
